// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dz3Binary.DAL.Context;

#nullable disable

namespace dz3Binary.DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20220712130111_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dz3Binary.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2022, 1, 14, 0, 1, 22, 950, DateTimeKind.Local).AddTicks(8054),
                            Deadline = new DateTime(2022, 9, 27, 21, 32, 6, 907, DateTimeKind.Local).AddTicks(1109),
                            Description = "Non doloremque esse qui et alias quidem.",
                            Name = "Web",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 26,
                            CreatedAt = new DateTime(2021, 10, 8, 22, 25, 31, 759, DateTimeKind.Local).AddTicks(6339),
                            Deadline = new DateTime(2022, 12, 9, 17, 26, 20, 912, DateTimeKind.Local).AddTicks(9045),
                            Description = "Quo totam laboriosam debitis veniam occaecati sed.",
                            Name = "Usability",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 15,
                            CreatedAt = new DateTime(2022, 6, 22, 16, 34, 34, 943, DateTimeKind.Local).AddTicks(3136),
                            Deadline = new DateTime(2022, 8, 30, 23, 5, 2, 21, DateTimeKind.Local).AddTicks(3531),
                            Description = "Magni necessitatibus quos quia illum qui et.",
                            Name = "Assurance",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2022, 3, 17, 15, 40, 36, 249, DateTimeKind.Local).AddTicks(821),
                            Deadline = new DateTime(2022, 12, 5, 19, 57, 26, 852, DateTimeKind.Local).AddTicks(8239),
                            Description = "Aspernatur sint harum expedita incidunt amet amet.",
                            Name = "Communications",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 21,
                            CreatedAt = new DateTime(2021, 12, 28, 17, 26, 44, 75, DateTimeKind.Local).AddTicks(9519),
                            Deadline = new DateTime(2023, 1, 21, 19, 47, 56, 328, DateTimeKind.Local).AddTicks(3618),
                            Description = "Vitae ut tempora inventore consequuntur rerum libero.",
                            Name = "Security",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 14,
                            CreatedAt = new DateTime(2021, 7, 28, 17, 33, 0, 152, DateTimeKind.Local).AddTicks(5072),
                            Deadline = new DateTime(2022, 12, 16, 19, 27, 7, 619, DateTimeKind.Local).AddTicks(9985),
                            Description = "Iusto dicta qui consectetur nisi culpa expedita.",
                            Name = "Marketing",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            CreatedAt = new DateTime(2022, 4, 20, 9, 37, 35, 659, DateTimeKind.Local).AddTicks(6915),
                            Deadline = new DateTime(2022, 12, 27, 4, 27, 18, 741, DateTimeKind.Local).AddTicks(4831),
                            Description = "Ea velit est et fugiat quisquam velit.",
                            Name = "Branding",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 20,
                            CreatedAt = new DateTime(2022, 2, 7, 16, 51, 53, 253, DateTimeKind.Local).AddTicks(6572),
                            Deadline = new DateTime(2023, 5, 19, 15, 11, 33, 121, DateTimeKind.Local).AddTicks(65),
                            Description = "Totam eaque natus exercitationem est possimus est.",
                            Name = "Usability",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 30,
                            CreatedAt = new DateTime(2021, 8, 1, 15, 57, 11, 393, DateTimeKind.Local).AddTicks(7350),
                            Deadline = new DateTime(2022, 10, 31, 14, 10, 14, 178, DateTimeKind.Local).AddTicks(3635),
                            Description = "Laudantium rem sunt labore temporibus tempora facilis.",
                            Name = "Implementation",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2022, 1, 6, 7, 42, 20, 431, DateTimeKind.Local).AddTicks(3336),
                            Deadline = new DateTime(2022, 8, 27, 12, 22, 11, 75, DateTimeKind.Local).AddTicks(6377),
                            Description = "Voluptatem facilis cum dolorum molestias mollitia quas.",
                            Name = "Factors",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 30,
                            CreatedAt = new DateTime(2022, 5, 20, 21, 32, 51, 656, DateTimeKind.Local).AddTicks(381),
                            Deadline = new DateTime(2023, 2, 5, 18, 35, 3, 257, DateTimeKind.Local).AddTicks(4763),
                            Description = "Non eligendi rerum iste commodi at sed.",
                            Name = "Mobility",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2021, 12, 12, 5, 56, 23, 57, DateTimeKind.Local).AddTicks(5569),
                            Deadline = new DateTime(2023, 5, 3, 16, 13, 50, 819, DateTimeKind.Local).AddTicks(4213),
                            Description = "Necessitatibus temporibus ut temporibus neque asperiores assumenda.",
                            Name = "Communications",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 21,
                            CreatedAt = new DateTime(2022, 3, 16, 1, 40, 30, 36, DateTimeKind.Local).AddTicks(9806),
                            Deadline = new DateTime(2023, 4, 1, 18, 14, 12, 688, DateTimeKind.Local).AddTicks(8174),
                            Description = "Iusto culpa repellat suscipit voluptas a recusandae.",
                            Name = "Data",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 26,
                            CreatedAt = new DateTime(2022, 3, 15, 8, 40, 3, 104, DateTimeKind.Local).AddTicks(4219),
                            Deadline = new DateTime(2023, 4, 13, 2, 15, 37, 430, DateTimeKind.Local).AddTicks(14),
                            Description = "Aut eos rerum quidem magnam officiis ipsum.",
                            Name = "Paradigm",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 17,
                            CreatedAt = new DateTime(2021, 12, 7, 5, 6, 45, 846, DateTimeKind.Local).AddTicks(524),
                            Deadline = new DateTime(2023, 1, 5, 16, 39, 29, 297, DateTimeKind.Local).AddTicks(9709),
                            Description = "Quia fugit voluptatem voluptas quasi maiores animi.",
                            Name = "Accounts",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 20,
                            CreatedAt = new DateTime(2021, 8, 30, 8, 50, 46, 212, DateTimeKind.Local).AddTicks(7829),
                            Deadline = new DateTime(2023, 4, 22, 20, 14, 39, 751, DateTimeKind.Local).AddTicks(9027),
                            Description = "Ea saepe quis non animi necessitatibus sit.",
                            Name = "Configuration",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2022, 3, 13, 18, 21, 31, 898, DateTimeKind.Local).AddTicks(9358),
                            Deadline = new DateTime(2023, 1, 22, 0, 43, 12, 372, DateTimeKind.Local).AddTicks(1774),
                            Description = "Quia aut modi at ipsam molestiae aut.",
                            Name = "Optimization",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 19,
                            CreatedAt = new DateTime(2022, 1, 9, 17, 10, 33, 506, DateTimeKind.Local).AddTicks(2756),
                            Deadline = new DateTime(2022, 8, 7, 22, 5, 18, 935, DateTimeKind.Local).AddTicks(8303),
                            Description = "Autem inventore id sequi dolorum velit aliquid.",
                            Name = "Security",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 30,
                            CreatedAt = new DateTime(2022, 5, 28, 18, 23, 38, 712, DateTimeKind.Local).AddTicks(4355),
                            Deadline = new DateTime(2022, 10, 28, 18, 42, 28, 770, DateTimeKind.Local).AddTicks(9742),
                            Description = "Quia a porro nisi praesentium libero voluptatum.",
                            Name = "Factors",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 11,
                            CreatedAt = new DateTime(2022, 5, 8, 18, 4, 19, 302, DateTimeKind.Local).AddTicks(2120),
                            Deadline = new DateTime(2022, 10, 23, 20, 57, 33, 529, DateTimeKind.Local).AddTicks(834),
                            Description = "Dolor qui deserunt facilis repudiandae inventore et.",
                            Name = "Mobility",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RenamedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 19, 7, 5, 50, 14, DateTimeKind.Local).AddTicks(2214),
                            Description = "Aliquam minima est velit aut.",
                            FinishedAt = new DateTime(2021, 9, 13, 1, 32, 10, 217, DateTimeKind.Local).AddTicks(6472),
                            PerformerId = 30,
                            ProjectId = 1,
                            RenamedName = "Burnice",
                            State = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 18, 21, 54, 7, 954, DateTimeKind.Local).AddTicks(7715),
                            Description = "Doloribus placeat aliquid sequi quis.",
                            FinishedAt = new DateTime(2021, 9, 22, 13, 39, 34, 242, DateTimeKind.Local).AddTicks(1234),
                            PerformerId = 17,
                            ProjectId = 7,
                            RenamedName = "Glenna",
                            State = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 4, 21, 46, 48, 737, DateTimeKind.Local).AddTicks(7314),
                            Description = "Aut cum voluptates provident aut.",
                            FinishedAt = new DateTime(2021, 11, 30, 13, 16, 0, 187, DateTimeKind.Local).AddTicks(5743),
                            PerformerId = 7,
                            ProjectId = 3,
                            RenamedName = "Emilio",
                            State = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 30, 21, 22, 57, 739, DateTimeKind.Local).AddTicks(6794),
                            Description = "Quia ex sint quia necessitatibus.",
                            FinishedAt = new DateTime(2021, 11, 20, 10, 38, 5, 933, DateTimeKind.Local).AddTicks(675),
                            PerformerId = 19,
                            ProjectId = 13,
                            RenamedName = "Merlin",
                            State = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 1, 13, 20, 51, 39, 746, DateTimeKind.Local).AddTicks(8618),
                            Description = "Minima cupiditate dolores rerum veritatis.",
                            FinishedAt = new DateTime(2021, 12, 26, 13, 22, 45, 192, DateTimeKind.Local).AddTicks(869),
                            PerformerId = 13,
                            ProjectId = 1,
                            RenamedName = "Mervin",
                            State = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 9, 20, 7, 24, 346, DateTimeKind.Local).AddTicks(5026),
                            Description = "Explicabo debitis aut autem maiores.",
                            PerformerId = 18,
                            ProjectId = 10,
                            RenamedName = "Gerald",
                            State = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 10, 3, 3, 50, 57, 396, DateTimeKind.Local).AddTicks(7581),
                            Description = "Voluptatem provident eaque et aperiam.",
                            FinishedAt = new DateTime(2022, 1, 6, 5, 58, 38, 559, DateTimeKind.Local).AddTicks(9701),
                            PerformerId = 21,
                            ProjectId = 1,
                            RenamedName = "Jeff",
                            State = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 15, 13, 59, 42, 267, DateTimeKind.Local).AddTicks(3500),
                            Description = "Blanditiis iure et quaerat quo.",
                            FinishedAt = new DateTime(2021, 10, 5, 11, 54, 9, 861, DateTimeKind.Local).AddTicks(9177),
                            PerformerId = 12,
                            ProjectId = 20,
                            RenamedName = "Geoffrey",
                            State = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 29, 21, 29, 32, 635, DateTimeKind.Local).AddTicks(4254),
                            Description = "Quibusdam similique deserunt velit harum.",
                            FinishedAt = new DateTime(2022, 7, 6, 21, 27, 53, 199, DateTimeKind.Local).AddTicks(7469),
                            PerformerId = 29,
                            ProjectId = 16,
                            RenamedName = "Lavina",
                            State = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 1, 11, 17, 23, 34, 727, DateTimeKind.Local).AddTicks(5819),
                            Description = "Quia et esse eum sit.",
                            FinishedAt = new DateTime(2021, 7, 21, 7, 36, 57, 67, DateTimeKind.Local).AddTicks(7141),
                            PerformerId = 14,
                            ProjectId = 15,
                            RenamedName = "Carter",
                            State = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 5, 31, 6, 6, 58, 577, DateTimeKind.Local).AddTicks(8160),
                            Description = "Facilis rerum voluptatem quod voluptate.",
                            PerformerId = 19,
                            ProjectId = 15,
                            RenamedName = "Carolina",
                            State = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 5, 1, 6, 15, 39, 474, DateTimeKind.Local).AddTicks(9691),
                            Description = "Ipsam incidunt neque beatae omnis.",
                            FinishedAt = new DateTime(2022, 3, 26, 17, 37, 1, 520, DateTimeKind.Local).AddTicks(141),
                            PerformerId = 21,
                            ProjectId = 15,
                            RenamedName = "Verlie",
                            State = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 8, 27, 8, 25, 22, 516, DateTimeKind.Local).AddTicks(63),
                            Description = "Non sunt labore eligendi quam.",
                            FinishedAt = new DateTime(2021, 11, 10, 5, 30, 10, 883, DateTimeKind.Local).AddTicks(7943),
                            PerformerId = 21,
                            ProjectId = 1,
                            RenamedName = "Nathanael",
                            State = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 6, 6, 1, 54, 59, 313, DateTimeKind.Local).AddTicks(5895),
                            Description = "Aut aut sit tenetur repellat.",
                            FinishedAt = new DateTime(2022, 3, 25, 18, 45, 19, 133, DateTimeKind.Local).AddTicks(8842),
                            PerformerId = 16,
                            ProjectId = 3,
                            RenamedName = "Tyler",
                            State = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 8, 22, 1, 26, 49, 395, DateTimeKind.Local).AddTicks(8484),
                            Description = "Alias perferendis quod nisi autem.",
                            PerformerId = 1,
                            ProjectId = 11,
                            RenamedName = "Imogene",
                            State = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 12, 5, 8, 19, 7, 517, DateTimeKind.Local).AddTicks(9080),
                            Description = "Sed nam qui eaque qui.",
                            PerformerId = 26,
                            ProjectId = 18,
                            RenamedName = "Otha",
                            State = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 5, 22, 12, 19, 6, 146, DateTimeKind.Local).AddTicks(1597),
                            Description = "Iure numquam aut repellendus quis.",
                            FinishedAt = new DateTime(2021, 9, 8, 17, 50, 47, 490, DateTimeKind.Local).AddTicks(3232),
                            PerformerId = 15,
                            ProjectId = 1,
                            RenamedName = "Taurean",
                            State = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 5, 30, 3, 52, 28, 317, DateTimeKind.Local).AddTicks(9602),
                            Description = "Iusto laborum saepe aut qui.",
                            PerformerId = 25,
                            ProjectId = 14,
                            RenamedName = "Friedrich",
                            State = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 1, 26, 15, 17, 25, 936, DateTimeKind.Local).AddTicks(1551),
                            Description = "Ratione optio quaerat ut quaerat.",
                            PerformerId = 27,
                            ProjectId = 11,
                            RenamedName = "Nico",
                            State = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 11, 7, 8, 42, 53, 363, DateTimeKind.Local).AddTicks(5723),
                            Description = "Qui fuga similique quia beatae.",
                            FinishedAt = new DateTime(2021, 12, 6, 20, 21, 9, 928, DateTimeKind.Local).AddTicks(8190),
                            PerformerId = 12,
                            ProjectId = 2,
                            RenamedName = "Josiah",
                            State = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 5, 21, 20, 42, 20, 891, DateTimeKind.Local).AddTicks(9309),
                            Description = "Aut autem vel quis officiis.",
                            FinishedAt = new DateTime(2022, 4, 22, 1, 53, 9, 814, DateTimeKind.Local).AddTicks(2518),
                            PerformerId = 26,
                            ProjectId = 19,
                            RenamedName = "Jarred",
                            State = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 8, 4, 16, 36, 52, 7, DateTimeKind.Local).AddTicks(5878),
                            Description = "Sed repudiandae rerum est facilis.",
                            FinishedAt = new DateTime(2021, 7, 17, 8, 24, 38, 345, DateTimeKind.Local).AddTicks(300),
                            PerformerId = 19,
                            ProjectId = 12,
                            RenamedName = "Arch",
                            State = 0
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 7, 21, 11, 39, 24, 649, DateTimeKind.Local).AddTicks(7951),
                            Description = "Quos veritatis aut expedita ducimus.",
                            FinishedAt = new DateTime(2022, 5, 12, 17, 6, 41, 418, DateTimeKind.Local).AddTicks(8207),
                            PerformerId = 2,
                            ProjectId = 7,
                            RenamedName = "Ervin",
                            State = 2
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 7, 20, 2, 15, 38, 433, DateTimeKind.Local).AddTicks(8169),
                            Description = "Dolorem dolores reiciendis dolor quos.",
                            PerformerId = 5,
                            ProjectId = 6,
                            RenamedName = "Camryn",
                            State = 2
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 11, 23, 0, 34, 50, 315, DateTimeKind.Local).AddTicks(1328),
                            Description = "Et eos quibusdam quia consequatur.",
                            FinishedAt = new DateTime(2022, 2, 9, 17, 35, 34, 609, DateTimeKind.Local).AddTicks(9054),
                            PerformerId = 11,
                            ProjectId = 17,
                            RenamedName = "Malinda",
                            State = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 7, 15, 10, 16, 30, 295, DateTimeKind.Local).AddTicks(726),
                            Description = "Accusantium praesentium aut suscipit id.",
                            FinishedAt = new DateTime(2021, 9, 16, 0, 42, 37, 972, DateTimeKind.Local).AddTicks(2374),
                            PerformerId = 1,
                            ProjectId = 1,
                            RenamedName = "Christine",
                            State = 3
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 1, 2, 5, 21, 30, 674, DateTimeKind.Local).AddTicks(1755),
                            Description = "Sed minima ex ut doloremque.",
                            FinishedAt = new DateTime(2021, 7, 19, 2, 40, 46, 916, DateTimeKind.Local).AddTicks(4552),
                            PerformerId = 22,
                            ProjectId = 17,
                            RenamedName = "Art",
                            State = 2
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 4, 21, 20, 22, 1, 679, DateTimeKind.Local).AddTicks(4657),
                            Description = "In sint est aut sunt.",
                            PerformerId = 28,
                            ProjectId = 7,
                            RenamedName = "Norene",
                            State = 2
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 5, 15, 12, 37, 3, 173, DateTimeKind.Local).AddTicks(4134),
                            Description = "Totam dolore ullam omnis excepturi.",
                            PerformerId = 26,
                            ProjectId = 7,
                            RenamedName = "Alphonso",
                            State = 0
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 9, 2, 0, 9, 27, 948, DateTimeKind.Local).AddTicks(3083),
                            Description = "Voluptatem tenetur et eligendi architecto.",
                            PerformerId = 3,
                            ProjectId = 2,
                            RenamedName = "Odie",
                            State = 2
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 3, 20, 3, 45, 15, 748, DateTimeKind.Local).AddTicks(2560),
                            Description = "Distinctio aut voluptatem accusantium aperiam.",
                            FinishedAt = new DateTime(2022, 3, 23, 9, 37, 28, 335, DateTimeKind.Local).AddTicks(9677),
                            PerformerId = 1,
                            ProjectId = 6,
                            RenamedName = "Mathilde",
                            State = 3
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 7, 17, 8, 12, 53, 380, DateTimeKind.Local).AddTicks(9716),
                            Description = "Omnis incidunt necessitatibus et est.",
                            FinishedAt = new DateTime(2021, 8, 3, 23, 55, 44, 310, DateTimeKind.Local).AddTicks(2067),
                            PerformerId = 8,
                            ProjectId = 8,
                            RenamedName = "Arjun",
                            State = 2
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 7, 1, 5, 24, 20, 277, DateTimeKind.Local).AddTicks(2800),
                            Description = "Delectus veniam temporibus voluptas consequuntur.",
                            FinishedAt = new DateTime(2022, 5, 27, 10, 57, 41, 312, DateTimeKind.Local).AddTicks(4778),
                            PerformerId = 12,
                            ProjectId = 18,
                            RenamedName = "Lauren",
                            State = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 8, 26, 0, 44, 53, 962, DateTimeKind.Local).AddTicks(3722),
                            Description = "Quidem voluptatibus vero non veritatis.",
                            FinishedAt = new DateTime(2022, 7, 4, 7, 28, 26, 197, DateTimeKind.Local).AddTicks(8177),
                            PerformerId = 4,
                            ProjectId = 1,
                            RenamedName = "Esther",
                            State = 0
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 10, 11, 2, 17, 59, 685, DateTimeKind.Local).AddTicks(3164),
                            Description = "Eos doloribus eos laborum corporis.",
                            PerformerId = 1,
                            ProjectId = 11,
                            RenamedName = "Ryan",
                            State = 3
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 12, 31, 23, 16, 23, 781, DateTimeKind.Local).AddTicks(1079),
                            Description = "Est vero deserunt labore fuga.",
                            FinishedAt = new DateTime(2022, 4, 4, 20, 26, 21, 842, DateTimeKind.Local).AddTicks(6080),
                            PerformerId = 2,
                            ProjectId = 17,
                            RenamedName = "Eduardo",
                            State = 2
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 8, 29, 8, 31, 50, 769, DateTimeKind.Local).AddTicks(6370),
                            Description = "Soluta repellendus alias aspernatur perspiciatis.",
                            FinishedAt = new DateTime(2022, 4, 7, 9, 7, 34, 407, DateTimeKind.Local).AddTicks(7424),
                            PerformerId = 24,
                            ProjectId = 2,
                            RenamedName = "Leland",
                            State = 3
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 10, 8, 9, 25, 47, 827, DateTimeKind.Local).AddTicks(7172),
                            Description = "Beatae sed reprehenderit consectetur velit.",
                            FinishedAt = new DateTime(2021, 11, 28, 23, 59, 10, 52, DateTimeKind.Local).AddTicks(6608),
                            PerformerId = 22,
                            ProjectId = 8,
                            RenamedName = "Gaetano",
                            State = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 11, 1, 18, 8, 15, 379, DateTimeKind.Local).AddTicks(1300),
                            Description = "Quaerat reprehenderit aliquam libero consectetur.",
                            FinishedAt = new DateTime(2022, 2, 12, 18, 32, 16, 284, DateTimeKind.Local).AddTicks(6183),
                            PerformerId = 6,
                            ProjectId = 9,
                            RenamedName = "Meredith",
                            State = 2
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2022, 1, 8, 4, 48, 24, 925, DateTimeKind.Local).AddTicks(3508),
                            Description = "Nostrum vel ut rerum eligendi.",
                            FinishedAt = new DateTime(2022, 1, 14, 9, 32, 29, 939, DateTimeKind.Local).AddTicks(894),
                            PerformerId = 15,
                            ProjectId = 8,
                            RenamedName = "Orrin",
                            State = 0
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2022, 2, 21, 4, 50, 15, 688, DateTimeKind.Local).AddTicks(8806),
                            Description = "A at inventore quos et.",
                            FinishedAt = new DateTime(2022, 4, 7, 1, 0, 48, 125, DateTimeKind.Local).AddTicks(8297),
                            PerformerId = 14,
                            ProjectId = 13,
                            RenamedName = "Dora",
                            State = 2
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 12, 13, 10, 55, 46, 182, DateTimeKind.Local).AddTicks(3977),
                            Description = "Nihil optio id et at.",
                            FinishedAt = new DateTime(2022, 2, 1, 2, 19, 3, 625, DateTimeKind.Local).AddTicks(5479),
                            PerformerId = 11,
                            ProjectId = 8,
                            RenamedName = "Donny",
                            State = 2
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2022, 4, 10, 20, 37, 25, 183, DateTimeKind.Local).AddTicks(4187),
                            Description = "Reprehenderit est molestias unde alias.",
                            FinishedAt = new DateTime(2022, 7, 12, 13, 42, 59, 879, DateTimeKind.Local).AddTicks(8494),
                            PerformerId = 20,
                            ProjectId = 5,
                            RenamedName = "Roberta",
                            State = 3
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2022, 4, 2, 8, 2, 39, 882, DateTimeKind.Local).AddTicks(5341),
                            Description = "Qui animi excepturi rerum nulla.",
                            FinishedAt = new DateTime(2022, 6, 27, 5, 28, 29, 167, DateTimeKind.Local).AddTicks(7876),
                            PerformerId = 15,
                            ProjectId = 10,
                            RenamedName = "Magdalena",
                            State = 3
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 11, 25, 13, 26, 10, 545, DateTimeKind.Local).AddTicks(8968),
                            Description = "Rem ad sed quis beatae.",
                            PerformerId = 23,
                            ProjectId = 1,
                            RenamedName = "Garrett",
                            State = 3
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 9, 21, 23, 8, 30, 670, DateTimeKind.Local).AddTicks(1555),
                            Description = "Accusamus tenetur veniam aut iusto.",
                            FinishedAt = new DateTime(2022, 5, 14, 8, 9, 40, 714, DateTimeKind.Local).AddTicks(9695),
                            PerformerId = 13,
                            ProjectId = 7,
                            RenamedName = "Declan",
                            State = 3
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2022, 6, 8, 22, 55, 19, 922, DateTimeKind.Local).AddTicks(2076),
                            Description = "Quam incidunt molestias et corrupti.",
                            FinishedAt = new DateTime(2022, 1, 29, 3, 56, 50, 372, DateTimeKind.Local).AddTicks(2057),
                            PerformerId = 18,
                            ProjectId = 16,
                            RenamedName = "Greyson",
                            State = 0
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2022, 4, 1, 1, 20, 21, 178, DateTimeKind.Local).AddTicks(6951),
                            Description = "Quia nesciunt officia facilis tenetur.",
                            PerformerId = 25,
                            ProjectId = 20,
                            RenamedName = "Aileen",
                            State = 0
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2022, 1, 30, 20, 30, 53, 352, DateTimeKind.Local).AddTicks(2792),
                            Description = "Odit et a omnis debitis.",
                            PerformerId = 2,
                            ProjectId = 4,
                            RenamedName = "Alda",
                            State = 3
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 8, 7, 5, 32, 1, 962, DateTimeKind.Local).AddTicks(1640),
                            Description = "Maiores eum dolorem voluptatem sed.",
                            FinishedAt = new DateTime(2022, 1, 8, 15, 46, 59, 784, DateTimeKind.Local).AddTicks(5845),
                            PerformerId = 21,
                            ProjectId = 15,
                            RenamedName = "London",
                            State = 1
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 9, 6, 12, 51, 5, 86, DateTimeKind.Local).AddTicks(2937),
                            Description = "Aperiam quisquam magnam iste enim.",
                            FinishedAt = new DateTime(2021, 9, 16, 4, 54, 37, 4, DateTimeKind.Local).AddTicks(7674),
                            PerformerId = 12,
                            ProjectId = 20,
                            RenamedName = "Madonna",
                            State = 1
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2021, 11, 8, 19, 24, 28, 512, DateTimeKind.Local).AddTicks(3814),
                            Description = "Fugiat ad et vel est.",
                            FinishedAt = new DateTime(2022, 4, 29, 5, 59, 45, 0, DateTimeKind.Local).AddTicks(8022),
                            PerformerId = 23,
                            ProjectId = 10,
                            RenamedName = "Kyler",
                            State = 0
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2021, 7, 25, 11, 32, 58, 895, DateTimeKind.Local).AddTicks(8233),
                            Description = "Est dolores tempore et voluptatem.",
                            FinishedAt = new DateTime(2022, 5, 20, 17, 12, 57, 460, DateTimeKind.Local).AddTicks(8763),
                            PerformerId = 13,
                            ProjectId = 2,
                            RenamedName = "Madisen",
                            State = 0
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2022, 1, 24, 0, 55, 12, 861, DateTimeKind.Local).AddTicks(5200),
                            Description = "Modi voluptatem voluptatem eius natus.",
                            FinishedAt = new DateTime(2021, 10, 31, 2, 33, 30, 754, DateTimeKind.Local).AddTicks(4953),
                            PerformerId = 15,
                            ProjectId = 5,
                            RenamedName = "Cristobal",
                            State = 1
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2021, 9, 15, 5, 4, 0, 448, DateTimeKind.Local).AddTicks(4032),
                            Description = "Commodi adipisci labore inventore mollitia.",
                            FinishedAt = new DateTime(2021, 7, 24, 12, 2, 52, 586, DateTimeKind.Local).AddTicks(6291),
                            PerformerId = 26,
                            ProjectId = 15,
                            RenamedName = "Kelton",
                            State = 2
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2021, 8, 22, 15, 18, 50, 76, DateTimeKind.Local).AddTicks(9248),
                            Description = "Et amet illum quia qui.",
                            FinishedAt = new DateTime(2021, 10, 26, 17, 32, 47, 976, DateTimeKind.Local).AddTicks(5167),
                            PerformerId = 21,
                            ProjectId = 6,
                            RenamedName = "Augusta",
                            State = 2
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2022, 6, 27, 11, 10, 55, 744, DateTimeKind.Local).AddTicks(6206),
                            Description = "Nihil sunt velit quo voluptatem.",
                            FinishedAt = new DateTime(2022, 3, 13, 2, 6, 7, 150, DateTimeKind.Local).AddTicks(4672),
                            PerformerId = 23,
                            ProjectId = 6,
                            RenamedName = "Alysha",
                            State = 2
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2022, 1, 12, 16, 39, 6, 207, DateTimeKind.Local).AddTicks(885),
                            Description = "Aperiam sint odit rerum accusamus.",
                            FinishedAt = new DateTime(2021, 8, 31, 11, 8, 10, 120, DateTimeKind.Local).AddTicks(2893),
                            PerformerId = 16,
                            ProjectId = 3,
                            RenamedName = "Maggie",
                            State = 3
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2022, 2, 11, 2, 10, 53, 260, DateTimeKind.Local).AddTicks(4977),
                            Description = "Quas dolorum consequatur est nihil.",
                            FinishedAt = new DateTime(2021, 8, 30, 1, 12, 44, 168, DateTimeKind.Local).AddTicks(5890),
                            PerformerId = 11,
                            ProjectId = 16,
                            RenamedName = "Leann",
                            State = 3
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2021, 9, 14, 23, 20, 29, 678, DateTimeKind.Local).AddTicks(7734),
                            Description = "Quam minus ut quis sit.",
                            FinishedAt = new DateTime(2022, 5, 14, 19, 0, 46, 196, DateTimeKind.Local).AddTicks(5977),
                            PerformerId = 21,
                            ProjectId = 19,
                            RenamedName = "Fabiola",
                            State = 3
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2022, 5, 31, 10, 7, 7, 426, DateTimeKind.Local).AddTicks(6083),
                            Description = "Sed voluptate velit nobis qui.",
                            FinishedAt = new DateTime(2021, 11, 9, 21, 22, 32, 764, DateTimeKind.Local).AddTicks(9814),
                            PerformerId = 25,
                            ProjectId = 15,
                            RenamedName = "Leda",
                            State = 2
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2022, 6, 28, 17, 54, 55, 689, DateTimeKind.Local).AddTicks(4158),
                            Description = "Et nostrum asperiores ipsa sunt.",
                            FinishedAt = new DateTime(2021, 9, 19, 11, 15, 6, 348, DateTimeKind.Local).AddTicks(2781),
                            PerformerId = 10,
                            ProjectId = 2,
                            RenamedName = "Grayce",
                            State = 0
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2021, 11, 7, 12, 16, 4, 905, DateTimeKind.Local).AddTicks(2474),
                            Description = "Enim dignissimos aut eos in.",
                            FinishedAt = new DateTime(2021, 12, 15, 19, 41, 29, 856, DateTimeKind.Local).AddTicks(9568),
                            PerformerId = 6,
                            ProjectId = 5,
                            RenamedName = "Tre",
                            State = 1
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2022, 5, 15, 23, 2, 55, 901, DateTimeKind.Local).AddTicks(1749),
                            Description = "Placeat accusamus cum eaque quia.",
                            PerformerId = 11,
                            ProjectId = 4,
                            RenamedName = "Kiarra",
                            State = 1
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2022, 4, 27, 5, 38, 52, 280, DateTimeKind.Local).AddTicks(835),
                            Description = "Molestiae ipsam aperiam quod quia.",
                            FinishedAt = new DateTime(2022, 4, 20, 9, 3, 38, 144, DateTimeKind.Local).AddTicks(1545),
                            PerformerId = 27,
                            ProjectId = 20,
                            RenamedName = "Ciara",
                            State = 0
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2022, 1, 27, 6, 59, 31, 380, DateTimeKind.Local).AddTicks(4471),
                            Description = "Quod modi eius et ex.",
                            FinishedAt = new DateTime(2022, 3, 30, 19, 42, 54, 179, DateTimeKind.Local).AddTicks(8750),
                            PerformerId = 10,
                            ProjectId = 7,
                            RenamedName = "Alene",
                            State = 0
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2021, 11, 27, 16, 16, 29, 988, DateTimeKind.Local).AddTicks(2973),
                            Description = "In laboriosam inventore molestiae sint.",
                            FinishedAt = new DateTime(2022, 5, 21, 23, 18, 43, 792, DateTimeKind.Local).AddTicks(3023),
                            PerformerId = 16,
                            ProjectId = 2,
                            RenamedName = "Quentin",
                            State = 2
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2021, 9, 16, 0, 35, 37, 303, DateTimeKind.Local).AddTicks(3047),
                            Description = "Eaque nulla vero beatae molestias.",
                            FinishedAt = new DateTime(2022, 4, 3, 1, 34, 18, 184, DateTimeKind.Local).AddTicks(3921),
                            PerformerId = 29,
                            ProjectId = 6,
                            RenamedName = "Erich",
                            State = 3
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2022, 5, 7, 18, 3, 16, 969, DateTimeKind.Local).AddTicks(7368),
                            Description = "Itaque voluptatibus ipsa sint ullam.",
                            FinishedAt = new DateTime(2022, 2, 28, 10, 4, 43, 990, DateTimeKind.Local).AddTicks(6502),
                            PerformerId = 13,
                            ProjectId = 1,
                            RenamedName = "Kamron",
                            State = 2
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2022, 1, 13, 10, 9, 24, 605, DateTimeKind.Local).AddTicks(729),
                            Description = "Enim reiciendis quasi voluptatem dolor.",
                            FinishedAt = new DateTime(2022, 2, 2, 7, 36, 50, 117, DateTimeKind.Local).AddTicks(8839),
                            PerformerId = 15,
                            ProjectId = 10,
                            RenamedName = "Rudolph",
                            State = 2
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2022, 1, 26, 0, 46, 51, 441, DateTimeKind.Local).AddTicks(2597),
                            Description = "Vitae minus sit quaerat rerum.",
                            PerformerId = 8,
                            ProjectId = 5,
                            RenamedName = "Jordan",
                            State = 0
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2022, 4, 3, 3, 9, 39, 101, DateTimeKind.Local).AddTicks(5447),
                            Description = "Asperiores voluptatem aut aut officia.",
                            FinishedAt = new DateTime(2022, 1, 2, 3, 14, 25, 73, DateTimeKind.Local).AddTicks(4650),
                            PerformerId = 5,
                            ProjectId = 18,
                            RenamedName = "Jillian",
                            State = 3
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2022, 1, 23, 21, 41, 3, 528, DateTimeKind.Local).AddTicks(308),
                            Description = "Eos incidunt quas est velit.",
                            FinishedAt = new DateTime(2022, 7, 8, 8, 22, 39, 835, DateTimeKind.Local).AddTicks(1985),
                            PerformerId = 19,
                            ProjectId = 9,
                            RenamedName = "Jennyfer",
                            State = 2
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2022, 6, 7, 6, 57, 13, 59, DateTimeKind.Local).AddTicks(5273),
                            Description = "Deleniti maxime laborum corrupti neque.",
                            PerformerId = 26,
                            ProjectId = 13,
                            RenamedName = "Victoria",
                            State = 1
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2021, 10, 15, 3, 34, 40, 431, DateTimeKind.Local).AddTicks(7540),
                            Description = "Praesentium optio totam pariatur voluptatem.",
                            FinishedAt = new DateTime(2022, 4, 26, 18, 6, 12, 591, DateTimeKind.Local).AddTicks(321),
                            PerformerId = 4,
                            ProjectId = 18,
                            RenamedName = "Ken",
                            State = 1
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2022, 2, 19, 3, 6, 44, 210, DateTimeKind.Local).AddTicks(4136),
                            Description = "Culpa velit quia harum qui.",
                            FinishedAt = new DateTime(2021, 10, 21, 4, 11, 37, 510, DateTimeKind.Local).AddTicks(3558),
                            PerformerId = 10,
                            ProjectId = 17,
                            RenamedName = "Crawford",
                            State = 1
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2021, 8, 20, 20, 19, 12, 992, DateTimeKind.Local).AddTicks(4740),
                            Description = "Eveniet minus dolorum voluptatem ab.",
                            FinishedAt = new DateTime(2021, 12, 13, 22, 55, 47, 254, DateTimeKind.Local).AddTicks(4645),
                            PerformerId = 13,
                            ProjectId = 6,
                            RenamedName = "Nelda",
                            State = 0
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2022, 2, 1, 17, 51, 21, 312, DateTimeKind.Local).AddTicks(252),
                            Description = "Et qui fugit ut et.",
                            FinishedAt = new DateTime(2021, 8, 23, 10, 25, 36, 434, DateTimeKind.Local).AddTicks(3117),
                            PerformerId = 20,
                            ProjectId = 13,
                            RenamedName = "Angelita",
                            State = 1
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2022, 4, 29, 9, 48, 34, 156, DateTimeKind.Local).AddTicks(9572),
                            Description = "Ea laudantium nisi maxime ratione.",
                            FinishedAt = new DateTime(2022, 2, 26, 14, 21, 16, 841, DateTimeKind.Local).AddTicks(9708),
                            PerformerId = 4,
                            ProjectId = 18,
                            RenamedName = "Emiliano",
                            State = 1
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2022, 1, 14, 23, 49, 47, 143, DateTimeKind.Local).AddTicks(7838),
                            Description = "Voluptatibus ad enim autem molestiae.",
                            FinishedAt = new DateTime(2021, 10, 4, 5, 25, 20, 480, DateTimeKind.Local).AddTicks(9137),
                            PerformerId = 14,
                            ProjectId = 8,
                            RenamedName = "Wallace",
                            State = 1
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2021, 10, 31, 9, 16, 52, 450, DateTimeKind.Local).AddTicks(8436),
                            Description = "Ut ea voluptate corrupti sunt.",
                            FinishedAt = new DateTime(2021, 9, 27, 6, 4, 28, 748, DateTimeKind.Local).AddTicks(4715),
                            PerformerId = 27,
                            ProjectId = 2,
                            RenamedName = "Stacey",
                            State = 0
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2021, 8, 15, 4, 59, 29, 868, DateTimeKind.Local).AddTicks(2128),
                            Description = "Possimus delectus et ipsa sit.",
                            FinishedAt = new DateTime(2022, 4, 15, 8, 21, 6, 458, DateTimeKind.Local).AddTicks(8574),
                            PerformerId = 14,
                            ProjectId = 3,
                            RenamedName = "Roxanne",
                            State = 0
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2021, 7, 20, 13, 58, 33, 536, DateTimeKind.Local).AddTicks(3624),
                            Description = "Nobis at dolor nobis excepturi.",
                            FinishedAt = new DateTime(2021, 11, 30, 6, 0, 8, 452, DateTimeKind.Local).AddTicks(6975),
                            PerformerId = 13,
                            ProjectId = 18,
                            RenamedName = "Carlee",
                            State = 3
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2022, 5, 26, 8, 9, 43, 376, DateTimeKind.Local).AddTicks(2709),
                            Description = "Tenetur ipsa sit sed ea.",
                            FinishedAt = new DateTime(2022, 4, 17, 10, 44, 38, 105, DateTimeKind.Local).AddTicks(3459),
                            PerformerId = 20,
                            ProjectId = 15,
                            RenamedName = "Jewell",
                            State = 3
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2021, 10, 18, 23, 51, 59, 511, DateTimeKind.Local).AddTicks(5183),
                            Description = "Occaecati porro eum sint doloremque.",
                            PerformerId = 14,
                            ProjectId = 7,
                            RenamedName = "Roscoe",
                            State = 1
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2022, 1, 29, 14, 55, 31, 137, DateTimeKind.Local).AddTicks(587),
                            Description = "Non officiis consequatur necessitatibus reprehenderit.",
                            PerformerId = 4,
                            ProjectId = 5,
                            RenamedName = "Dorian",
                            State = 2
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2021, 11, 24, 7, 25, 22, 14, DateTimeKind.Local).AddTicks(5310),
                            Description = "Consequatur id voluptatem aut ratione.",
                            FinishedAt = new DateTime(2022, 2, 18, 0, 31, 42, 751, DateTimeKind.Local).AddTicks(1348),
                            PerformerId = 26,
                            ProjectId = 5,
                            RenamedName = "Bradley",
                            State = 0
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2022, 4, 8, 15, 15, 42, 803, DateTimeKind.Local).AddTicks(5149),
                            Description = "Sint asperiores totam est modi.",
                            FinishedAt = new DateTime(2022, 3, 28, 20, 28, 25, 929, DateTimeKind.Local).AddTicks(956),
                            PerformerId = 28,
                            ProjectId = 19,
                            RenamedName = "Blanca",
                            State = 0
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2022, 1, 6, 3, 53, 49, 734, DateTimeKind.Local).AddTicks(6722),
                            Description = "Maxime pariatur sit et aut.",
                            PerformerId = 11,
                            ProjectId = 16,
                            RenamedName = "Yvonne",
                            State = 2
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2022, 6, 16, 8, 24, 44, 89, DateTimeKind.Local).AddTicks(3804),
                            Description = "Quis officia optio ipsum quia.",
                            FinishedAt = new DateTime(2021, 10, 15, 23, 56, 44, 826, DateTimeKind.Local).AddTicks(4203),
                            PerformerId = 22,
                            ProjectId = 7,
                            RenamedName = "Norbert",
                            State = 1
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2021, 8, 7, 22, 43, 43, 743, DateTimeKind.Local).AddTicks(9056),
                            Description = "Ea est adipisci rerum necessitatibus.",
                            FinishedAt = new DateTime(2021, 10, 25, 13, 52, 7, 139, DateTimeKind.Local).AddTicks(3922),
                            PerformerId = 2,
                            ProjectId = 16,
                            RenamedName = "Ines",
                            State = 2
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2021, 10, 9, 18, 10, 6, 308, DateTimeKind.Local).AddTicks(3190),
                            Description = "Necessitatibus exercitationem rerum ullam accusantium.",
                            FinishedAt = new DateTime(2022, 6, 12, 7, 44, 59, 959, DateTimeKind.Local).AddTicks(5508),
                            PerformerId = 26,
                            ProjectId = 15,
                            RenamedName = "Hyman",
                            State = 2
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2021, 8, 31, 21, 26, 43, 153, DateTimeKind.Local).AddTicks(4672),
                            Description = "Vero necessitatibus quia nemo velit.",
                            FinishedAt = new DateTime(2021, 11, 5, 23, 40, 26, 821, DateTimeKind.Local).AddTicks(8674),
                            PerformerId = 22,
                            ProjectId = 10,
                            RenamedName = "Nedra",
                            State = 3
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2021, 12, 1, 11, 49, 33, 820, DateTimeKind.Local).AddTicks(9054),
                            Description = "Ipsam eaque rerum voluptates modi.",
                            PerformerId = 27,
                            ProjectId = 11,
                            RenamedName = "Leila",
                            State = 3
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2021, 11, 27, 6, 43, 17, 873, DateTimeKind.Local).AddTicks(8238),
                            Description = "Ipsum et velit quas rerum.",
                            FinishedAt = new DateTime(2022, 5, 1, 2, 39, 44, 423, DateTimeKind.Local).AddTicks(8034),
                            PerformerId = 1,
                            ProjectId = 15,
                            RenamedName = "Gregoria",
                            State = 2
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2021, 9, 2, 12, 44, 37, 513, DateTimeKind.Local).AddTicks(9912),
                            Description = "Et molestiae est ut architecto.",
                            FinishedAt = new DateTime(2022, 5, 2, 21, 7, 20, 563, DateTimeKind.Local).AddTicks(5237),
                            PerformerId = 26,
                            ProjectId = 1,
                            RenamedName = "Jaleel",
                            State = 2
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2021, 11, 25, 5, 56, 59, 284, DateTimeKind.Local).AddTicks(9395),
                            Description = "Suscipit tempore tempora sequi deleniti.",
                            FinishedAt = new DateTime(2021, 9, 18, 9, 52, 21, 514, DateTimeKind.Local).AddTicks(6479),
                            PerformerId = 15,
                            ProjectId = 16,
                            RenamedName = "Emery",
                            State = 1
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2021, 12, 23, 11, 32, 54, 639, DateTimeKind.Local).AddTicks(3933),
                            Description = "Modi nesciunt distinctio eaque facere.",
                            FinishedAt = new DateTime(2021, 11, 18, 6, 20, 54, 389, DateTimeKind.Local).AddTicks(6183),
                            PerformerId = 16,
                            ProjectId = 11,
                            RenamedName = "Rita",
                            State = 2
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2022, 6, 6, 7, 40, 15, 340, DateTimeKind.Local).AddTicks(7474),
                            Description = "Quis est perspiciatis in rerum.",
                            FinishedAt = new DateTime(2021, 10, 15, 23, 41, 54, 477, DateTimeKind.Local).AddTicks(7306),
                            PerformerId = 16,
                            ProjectId = 3,
                            RenamedName = "Ara",
                            State = 3
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2022, 3, 10, 21, 21, 30, 864, DateTimeKind.Local).AddTicks(1057),
                            Description = "Eos id quo eos assumenda.",
                            FinishedAt = new DateTime(2021, 9, 11, 22, 17, 9, 993, DateTimeKind.Local).AddTicks(2903),
                            PerformerId = 10,
                            ProjectId = 5,
                            RenamedName = "Mohammad",
                            State = 1
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 4, 5, 44, 44, 388, DateTimeKind.Local).AddTicks(4973),
                            Name = "Dibbert - Fritsch"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 12, 3, 17, 50, 9, 661, DateTimeKind.Local).AddTicks(1570),
                            Name = "Mayert - Block"
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2021, 8, 20, 17, 28, 45, 981, DateTimeKind.Local).AddTicks(6979),
                            Email = "Sven_Goldner18@yahoo.com",
                            FirstName = "Danielle",
                            LastName = "Nitzsche",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 5, 14, 2, 47, 40, 984, DateTimeKind.Local).AddTicks(4786),
                            Email = "Jensen.Goldner39@gmail.com",
                            FirstName = "Jacklyn",
                            LastName = "Mohr",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2022, 7, 1, 5, 23, 23, 160, DateTimeKind.Local).AddTicks(7612),
                            Email = "Maye.Kiehn79@yahoo.com",
                            FirstName = "Ruby",
                            LastName = "Farrell",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2021, 10, 10, 8, 14, 1, 869, DateTimeKind.Local).AddTicks(9169),
                            Email = "Agustin88@hotmail.com",
                            FirstName = "Viola",
                            LastName = "Hand",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(2021, 11, 18, 19, 45, 31, 806, DateTimeKind.Local).AddTicks(4507),
                            Email = "Winston_Kirlin@yahoo.com",
                            FirstName = "Fletcher",
                            LastName = "Williamson",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            BirthDay = new DateTime(2021, 11, 28, 0, 3, 37, 682, DateTimeKind.Local).AddTicks(2740),
                            Email = "Talon55@gmail.com",
                            FirstName = "Greyson",
                            LastName = "Streich",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            BirthDay = new DateTime(2022, 2, 11, 12, 48, 55, 217, DateTimeKind.Local).AddTicks(1745),
                            Email = "Jean59@gmail.com",
                            FirstName = "Kendrick",
                            LastName = "Pouros",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            BirthDay = new DateTime(2021, 8, 23, 3, 56, 35, 946, DateTimeKind.Local).AddTicks(2435),
                            Email = "Ricardo81@yahoo.com",
                            FirstName = "Gregorio",
                            LastName = "Doyle",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            BirthDay = new DateTime(2022, 6, 11, 15, 30, 53, 282, DateTimeKind.Local).AddTicks(8595),
                            Email = "Wilfrid_Hackett@yahoo.com",
                            FirstName = "Bryce",
                            LastName = "Kuvalis",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            BirthDay = new DateTime(2021, 9, 16, 22, 35, 17, 144, DateTimeKind.Local).AddTicks(3837),
                            Email = "Vito_Schneider63@hotmail.com",
                            FirstName = "Catalina",
                            LastName = "Moen",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            BirthDay = new DateTime(2021, 8, 6, 15, 2, 4, 26, DateTimeKind.Local).AddTicks(5476),
                            Email = "Jayde79@gmail.com",
                            FirstName = "Roderick",
                            LastName = "Kutch",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            BirthDay = new DateTime(2022, 6, 20, 5, 49, 43, 781, DateTimeKind.Local).AddTicks(5044),
                            Email = "Pauline.Yundt39@gmail.com",
                            FirstName = "Newell",
                            LastName = "Gleichner",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            BirthDay = new DateTime(2022, 1, 3, 12, 1, 44, 516, DateTimeKind.Local).AddTicks(6657),
                            Email = "Jaren.Rippin@yahoo.com",
                            FirstName = "Virgie",
                            LastName = "Rohan",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            BirthDay = new DateTime(2022, 2, 16, 10, 9, 25, 798, DateTimeKind.Local).AddTicks(4380),
                            Email = "Ed_Mann@hotmail.com",
                            FirstName = "Gayle",
                            LastName = "Muller",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 15,
                            BirthDay = new DateTime(2021, 8, 31, 9, 54, 4, 130, DateTimeKind.Local).AddTicks(2829),
                            Email = "Austyn.Fisher49@hotmail.com",
                            FirstName = "Addison",
                            LastName = "Hoppe",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 16,
                            BirthDay = new DateTime(2021, 11, 15, 16, 22, 23, 978, DateTimeKind.Local).AddTicks(9041),
                            Email = "Milton_Mosciski@gmail.com",
                            FirstName = "Clair",
                            LastName = "Kuhn",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 17,
                            BirthDay = new DateTime(2022, 4, 21, 22, 29, 27, 839, DateTimeKind.Local).AddTicks(1644),
                            Email = "Austen.Dare72@hotmail.com",
                            FirstName = "Britney",
                            LastName = "Schimmel",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            BirthDay = new DateTime(2021, 11, 21, 10, 11, 23, 354, DateTimeKind.Local).AddTicks(9757),
                            Email = "Annetta.Effertz@yahoo.com",
                            FirstName = "Elroy",
                            LastName = "Abernathy",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 19,
                            BirthDay = new DateTime(2022, 7, 7, 0, 38, 12, 206, DateTimeKind.Local).AddTicks(2502),
                            Email = "Rolando7@hotmail.com",
                            FirstName = "Josefina",
                            LastName = "Hettinger",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            BirthDay = new DateTime(2021, 12, 4, 3, 4, 10, 385, DateTimeKind.Local).AddTicks(3691),
                            Email = "Marjolaine.Satterfield@gmail.com",
                            FirstName = "Neva",
                            LastName = "O'Hara",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            BirthDay = new DateTime(2022, 3, 10, 12, 21, 5, 52, DateTimeKind.Local).AddTicks(902),
                            Email = "Oswaldo97@yahoo.com",
                            FirstName = "Ettie",
                            LastName = "Ziemann",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 22,
                            BirthDay = new DateTime(2021, 12, 28, 3, 8, 55, 901, DateTimeKind.Local).AddTicks(7622),
                            Email = "Arlie89@gmail.com",
                            FirstName = "Hans",
                            LastName = "Jacobson",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 23,
                            BirthDay = new DateTime(2021, 12, 20, 9, 20, 52, 306, DateTimeKind.Local).AddTicks(9015),
                            Email = "Mikayla21@yahoo.com",
                            FirstName = "Kristy",
                            LastName = "Huels",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 24,
                            BirthDay = new DateTime(2021, 10, 25, 13, 45, 34, 803, DateTimeKind.Local).AddTicks(5193),
                            Email = "Perry71@hotmail.com",
                            FirstName = "Jaquan",
                            LastName = "Lang",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 25,
                            BirthDay = new DateTime(2022, 6, 15, 4, 38, 35, 298, DateTimeKind.Local).AddTicks(6290),
                            Email = "Jayce32@hotmail.com",
                            FirstName = "Una",
                            LastName = "Macejkovic",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 26,
                            BirthDay = new DateTime(2021, 9, 14, 12, 41, 9, 550, DateTimeKind.Local).AddTicks(2315),
                            Email = "Frederik59@yahoo.com",
                            FirstName = "Nelle",
                            LastName = "Feil",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 27,
                            BirthDay = new DateTime(2022, 7, 5, 19, 49, 3, 818, DateTimeKind.Local).AddTicks(5866),
                            Email = "Elna_Streich79@gmail.com",
                            FirstName = "Dora",
                            LastName = "Veum",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 28,
                            BirthDay = new DateTime(2022, 1, 30, 12, 44, 17, 897, DateTimeKind.Local).AddTicks(2857),
                            Email = "Bradford34@hotmail.com",
                            FirstName = "Lucious",
                            LastName = "Johns",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 29,
                            BirthDay = new DateTime(2021, 8, 26, 10, 36, 57, 226, DateTimeKind.Local).AddTicks(87),
                            Email = "Jasper_Price61@hotmail.com",
                            FirstName = "Charity",
                            LastName = "Treutel",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 30,
                            BirthDay = new DateTime(2021, 12, 7, 2, 48, 18, 595, DateTimeKind.Local).AddTicks(5275),
                            Email = "Juliana_Bernier18@hotmail.com",
                            FirstName = "Andy",
                            LastName = "Bailey",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Project", b =>
                {
                    b.HasOne("dz3Binary.DAL.Entities.User", "Author")
                        .WithMany("ProjectsCreated")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dz3Binary.DAL.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Task", b =>
                {
                    b.HasOne("dz3Binary.DAL.Entities.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dz3Binary.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dz3Binary.DAL.Entities.User", null)
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");

                    b.Navigation("Performer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.User", b =>
                {
                    b.HasOne("dz3Binary.DAL.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.User", b =>
                {
                    b.Navigation("ProjectsCreated");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
