// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dz3Binary.DAL.Context;

#nullable disable

namespace dz3Binary.DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20220712115310_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dz3Binary.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2022, 5, 12, 15, 12, 59, 649, DateTimeKind.Local).AddTicks(8769),
                            Deadline = new DateTime(2022, 8, 1, 16, 32, 29, 600, DateTimeKind.Local).AddTicks(6945),
                            Description = "Et dignissimos consequatur non exercitationem blanditiis cupiditate.",
                            Name = "Assurance",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 25,
                            CreatedAt = new DateTime(2022, 4, 22, 10, 10, 37, 5, DateTimeKind.Local).AddTicks(9142),
                            Deadline = new DateTime(2022, 10, 27, 19, 43, 57, 811, DateTimeKind.Local).AddTicks(6615),
                            Description = "Odio aliquam blanditiis quia numquam vero nisi.",
                            Name = "Mobility",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 23,
                            CreatedAt = new DateTime(2022, 5, 16, 15, 26, 1, 727, DateTimeKind.Local).AddTicks(2848),
                            Deadline = new DateTime(2022, 8, 2, 15, 55, 13, 378, DateTimeKind.Local).AddTicks(3995),
                            Description = "Facilis vel nihil beatae non impedit non.",
                            Name = "Branding",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 22,
                            CreatedAt = new DateTime(2021, 9, 14, 11, 41, 10, 751, DateTimeKind.Local).AddTicks(6550),
                            Deadline = new DateTime(2022, 12, 29, 4, 40, 55, 411, DateTimeKind.Local).AddTicks(3967),
                            Description = "Eligendi ut impedit dolores mollitia eos totam.",
                            Name = "Program",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 21,
                            CreatedAt = new DateTime(2022, 1, 13, 10, 5, 50, 907, DateTimeKind.Local).AddTicks(6118),
                            Deadline = new DateTime(2023, 3, 28, 10, 52, 54, 462, DateTimeKind.Local).AddTicks(2821),
                            Description = "Est voluptatem cupiditate nam et distinctio velit.",
                            Name = "Directives",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 1, 6, 8, 49, 18, 233, DateTimeKind.Local).AddTicks(7088),
                            Deadline = new DateTime(2023, 6, 1, 22, 18, 54, 503, DateTimeKind.Local).AddTicks(6664),
                            Description = "Aut aliquam voluptatem est quam voluptatem repudiandae.",
                            Name = "Directives",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 22,
                            CreatedAt = new DateTime(2021, 9, 8, 21, 16, 57, 82, DateTimeKind.Local).AddTicks(9288),
                            Deadline = new DateTime(2023, 2, 6, 22, 45, 2, 460, DateTimeKind.Local).AddTicks(9845),
                            Description = "Voluptatibus in ipsa eius corporis odio explicabo.",
                            Name = "Integration",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 27,
                            CreatedAt = new DateTime(2021, 11, 9, 10, 44, 20, 748, DateTimeKind.Local).AddTicks(9621),
                            Deadline = new DateTime(2022, 9, 17, 15, 3, 46, 468, DateTimeKind.Local).AddTicks(7136),
                            Description = "Labore rerum magnam nesciunt sed ipsum quidem.",
                            Name = "Marketing",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            CreatedAt = new DateTime(2021, 10, 15, 5, 5, 44, 786, DateTimeKind.Local).AddTicks(724),
                            Deadline = new DateTime(2022, 8, 2, 7, 19, 50, 57, DateTimeKind.Local).AddTicks(8686),
                            Description = "Quia occaecati alias vero ipsum dolor qui.",
                            Name = "Intranet",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 22,
                            CreatedAt = new DateTime(2021, 9, 28, 7, 0, 9, 716, DateTimeKind.Local).AddTicks(5110),
                            Deadline = new DateTime(2022, 10, 13, 6, 42, 27, 361, DateTimeKind.Local).AddTicks(6647),
                            Description = "Eveniet saepe nihil reiciendis cupiditate distinctio quas.",
                            Name = "Usability",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2022, 1, 2, 12, 48, 24, 661, DateTimeKind.Local).AddTicks(8422),
                            Deadline = new DateTime(2022, 12, 7, 10, 17, 31, 992, DateTimeKind.Local).AddTicks(9132),
                            Description = "Veritatis placeat cum numquam nihil esse soluta.",
                            Name = "Interactions",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 26,
                            CreatedAt = new DateTime(2021, 9, 4, 16, 55, 30, 749, DateTimeKind.Local).AddTicks(413),
                            Deadline = new DateTime(2023, 2, 7, 8, 27, 51, 7, DateTimeKind.Local).AddTicks(3247),
                            Description = "Quia debitis quaerat natus sit qui magni.",
                            Name = "Usability",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2022, 2, 23, 11, 52, 55, 936, DateTimeKind.Local).AddTicks(9128),
                            Deadline = new DateTime(2022, 10, 8, 14, 25, 11, 596, DateTimeKind.Local).AddTicks(8855),
                            Description = "Autem sint repellendus autem quis aut dolore.",
                            Name = "Creative",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 22,
                            CreatedAt = new DateTime(2022, 6, 26, 7, 15, 34, 706, DateTimeKind.Local).AddTicks(9906),
                            Deadline = new DateTime(2022, 10, 27, 8, 52, 52, 668, DateTimeKind.Local).AddTicks(8993),
                            Description = "Cum qui ullam sit facilis quibusdam earum.",
                            Name = "Infrastructure",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 16,
                            CreatedAt = new DateTime(2022, 5, 26, 10, 12, 16, 541, DateTimeKind.Local).AddTicks(5030),
                            Deadline = new DateTime(2023, 2, 4, 2, 14, 21, 126, DateTimeKind.Local).AddTicks(7642),
                            Description = "Quasi consequatur quod sunt necessitatibus est laborum.",
                            Name = "Markets",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 22,
                            CreatedAt = new DateTime(2022, 5, 9, 11, 45, 39, 396, DateTimeKind.Local).AddTicks(8561),
                            Deadline = new DateTime(2023, 4, 26, 20, 40, 5, 120, DateTimeKind.Local).AddTicks(4039),
                            Description = "In hic quod voluptatem ex temporibus rerum.",
                            Name = "Usability",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2022, 2, 20, 18, 19, 35, 831, DateTimeKind.Local).AddTicks(8639),
                            Deadline = new DateTime(2022, 10, 19, 6, 54, 31, 845, DateTimeKind.Local).AddTicks(146),
                            Description = "Omnis ex sint est quod nisi officia.",
                            Name = "Identity",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 17,
                            CreatedAt = new DateTime(2021, 9, 27, 15, 1, 9, 685, DateTimeKind.Local).AddTicks(8767),
                            Deadline = new DateTime(2023, 4, 26, 19, 33, 15, 541, DateTimeKind.Local).AddTicks(6671),
                            Description = "Consequatur sit neque quia ut tempore laboriosam.",
                            Name = "Marketing",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 25,
                            CreatedAt = new DateTime(2021, 10, 2, 5, 55, 17, 456, DateTimeKind.Local).AddTicks(6695),
                            Deadline = new DateTime(2022, 12, 22, 11, 15, 39, 343, DateTimeKind.Local).AddTicks(5334),
                            Description = "Ipsa unde maiores in ut earum nobis.",
                            Name = "Group",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 22,
                            CreatedAt = new DateTime(2021, 10, 20, 5, 14, 14, 92, DateTimeKind.Local).AddTicks(3548),
                            Deadline = new DateTime(2022, 9, 12, 14, 37, 26, 66, DateTimeKind.Local).AddTicks(5764),
                            Description = "Sunt pariatur est cumque ea optio ipsum.",
                            Name = "Accounts",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RenamedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 17, 40, 2, 470, DateTimeKind.Local).AddTicks(8072),
                            Description = "Earum neque et consequatur vel.",
                            FinishedAt = new DateTime(2022, 5, 14, 20, 40, 10, 270, DateTimeKind.Local).AddTicks(8417),
                            PerformerId = 24,
                            ProjectId = 17,
                            RenamedName = "Emerson",
                            State = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 6, 2, 18, 36, 25, 962, DateTimeKind.Local).AddTicks(4381),
                            Description = "Necessitatibus aliquid similique dolores nulla.",
                            PerformerId = 9,
                            ProjectId = 7,
                            RenamedName = "Wilhelmine",
                            State = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 20, 18, 15, 54, 195, DateTimeKind.Local).AddTicks(9985),
                            Description = "Porro eum quod tenetur labore.",
                            PerformerId = 16,
                            ProjectId = 1,
                            RenamedName = "Lawson",
                            State = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 12, 21, 5, 45, 22, 89, DateTimeKind.Local).AddTicks(3952),
                            Description = "Aspernatur eum sunt ea sed.",
                            FinishedAt = new DateTime(2021, 11, 22, 14, 12, 26, 514, DateTimeKind.Local).AddTicks(2639),
                            PerformerId = 12,
                            ProjectId = 14,
                            RenamedName = "Corene",
                            State = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 28, 9, 1, 58, 844, DateTimeKind.Local).AddTicks(9114),
                            Description = "Adipisci qui voluptate magnam rerum.",
                            FinishedAt = new DateTime(2021, 12, 24, 19, 58, 21, 937, DateTimeKind.Local).AddTicks(3870),
                            PerformerId = 25,
                            ProjectId = 7,
                            RenamedName = "Carley",
                            State = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 26, 19, 52, 10, 9, DateTimeKind.Local).AddTicks(2329),
                            Description = "Corrupti quo eaque magnam sit.",
                            FinishedAt = new DateTime(2021, 11, 27, 10, 42, 23, 371, DateTimeKind.Local).AddTicks(3300),
                            PerformerId = 20,
                            ProjectId = 14,
                            RenamedName = "Desiree",
                            State = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 6, 8, 12, 21, 58, 191, DateTimeKind.Local).AddTicks(4161),
                            Description = "Esse eos itaque amet illum.",
                            FinishedAt = new DateTime(2022, 6, 19, 12, 15, 1, 259, DateTimeKind.Local).AddTicks(9624),
                            PerformerId = 29,
                            ProjectId = 10,
                            RenamedName = "Terrell",
                            State = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 27, 1, 38, 55, 833, DateTimeKind.Local).AddTicks(6125),
                            Description = "Minus nobis et aut possimus.",
                            FinishedAt = new DateTime(2021, 9, 22, 2, 49, 31, 81, DateTimeKind.Local).AddTicks(1254),
                            PerformerId = 17,
                            ProjectId = 12,
                            RenamedName = "Maxime",
                            State = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 5, 17, 56, 20, 533, DateTimeKind.Local).AddTicks(6130),
                            Description = "Itaque ab quam quos aperiam.",
                            FinishedAt = new DateTime(2022, 3, 10, 1, 19, 23, 333, DateTimeKind.Local).AddTicks(2329),
                            PerformerId = 14,
                            ProjectId = 2,
                            RenamedName = "Chelsea",
                            State = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 4, 22, 16, 23, 7, 212, DateTimeKind.Local).AddTicks(8389),
                            Description = "Sapiente et illo similique molestiae.",
                            PerformerId = 15,
                            ProjectId = 14,
                            RenamedName = "Dina",
                            State = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 1, 15, 0, 44, 25, 590, DateTimeKind.Local).AddTicks(2676),
                            Description = "Aperiam qui et et error.",
                            PerformerId = 5,
                            ProjectId = 18,
                            RenamedName = "Oswaldo",
                            State = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 10, 27, 19, 10, 9, 63, DateTimeKind.Local).AddTicks(7753),
                            Description = "Harum voluptatem quae quo sed.",
                            FinishedAt = new DateTime(2022, 4, 18, 0, 27, 30, 953, DateTimeKind.Local).AddTicks(4138),
                            PerformerId = 1,
                            ProjectId = 4,
                            RenamedName = "Randi",
                            State = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 8, 14, 17, 30, 5, 204, DateTimeKind.Local).AddTicks(7629),
                            Description = "Aut voluptas culpa nemo alias.",
                            FinishedAt = new DateTime(2021, 8, 21, 17, 59, 33, 79, DateTimeKind.Local).AddTicks(2305),
                            PerformerId = 17,
                            ProjectId = 10,
                            RenamedName = "Rudolph",
                            State = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 6, 6, 4, 38, 14, 104, DateTimeKind.Local).AddTicks(2404),
                            Description = "Eos velit rem ducimus recusandae.",
                            FinishedAt = new DateTime(2021, 12, 30, 4, 38, 36, 988, DateTimeKind.Local).AddTicks(5857),
                            PerformerId = 4,
                            ProjectId = 1,
                            RenamedName = "Dayton",
                            State = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 3, 15, 22, 55, 24, 303, DateTimeKind.Local).AddTicks(5863),
                            Description = "Tempora illum error a esse.",
                            FinishedAt = new DateTime(2022, 2, 14, 3, 34, 28, 781, DateTimeKind.Local).AddTicks(5746),
                            PerformerId = 29,
                            ProjectId = 6,
                            RenamedName = "Osbaldo",
                            State = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 2, 1, 2, 26, 53, 302, DateTimeKind.Local).AddTicks(5553),
                            Description = "Laudantium enim ut sunt sed.",
                            PerformerId = 1,
                            ProjectId = 7,
                            RenamedName = "Liam",
                            State = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 12, 27, 14, 1, 1, 284, DateTimeKind.Local).AddTicks(7261),
                            Description = "Laboriosam minus et veniam voluptas.",
                            PerformerId = 5,
                            ProjectId = 10,
                            RenamedName = "Lauryn",
                            State = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 5, 22, 19, 18, 47, 402, DateTimeKind.Local).AddTicks(1110),
                            Description = "Assumenda consequatur voluptatibus veniam harum.",
                            FinishedAt = new DateTime(2021, 8, 19, 3, 51, 37, 217, DateTimeKind.Local).AddTicks(6641),
                            PerformerId = 23,
                            ProjectId = 19,
                            RenamedName = "Geo",
                            State = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 6, 14, 1, 16, 11, 431, DateTimeKind.Local).AddTicks(2307),
                            Description = "In magni non eos sit.",
                            FinishedAt = new DateTime(2022, 3, 19, 2, 1, 27, 735, DateTimeKind.Local).AddTicks(668),
                            PerformerId = 12,
                            ProjectId = 8,
                            RenamedName = "Isobel",
                            State = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 8, 5, 15, 31, 17, 440, DateTimeKind.Local).AddTicks(2275),
                            Description = "Quis qui labore totam qui.",
                            FinishedAt = new DateTime(2021, 12, 10, 10, 31, 13, 160, DateTimeKind.Local).AddTicks(8052),
                            PerformerId = 6,
                            ProjectId = 6,
                            RenamedName = "Ellis",
                            State = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 11, 28, 10, 25, 12, 230, DateTimeKind.Local).AddTicks(2415),
                            Description = "Assumenda voluptas repellendus voluptatem itaque.",
                            PerformerId = 22,
                            ProjectId = 17,
                            RenamedName = "Dessie",
                            State = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 3, 4, 1, 6, 33, 615, DateTimeKind.Local).AddTicks(8899),
                            Description = "In fugit ea velit velit.",
                            PerformerId = 17,
                            ProjectId = 1,
                            RenamedName = "Loraine",
                            State = 2
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 9, 5, 10, 24, 0, 892, DateTimeKind.Local).AddTicks(2700),
                            Description = "Quia et quidem sint illo.",
                            FinishedAt = new DateTime(2021, 12, 7, 12, 23, 43, 445, DateTimeKind.Local).AddTicks(8249),
                            PerformerId = 10,
                            ProjectId = 6,
                            RenamedName = "Marina",
                            State = 0
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 12, 14, 19, 35, 20, 36, DateTimeKind.Local).AddTicks(2012),
                            Description = "Qui consequatur in a pariatur.",
                            FinishedAt = new DateTime(2022, 1, 6, 20, 7, 52, 336, DateTimeKind.Local).AddTicks(2613),
                            PerformerId = 16,
                            ProjectId = 4,
                            RenamedName = "Madison",
                            State = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 6, 1, 22, 1, 18, 486, DateTimeKind.Local).AddTicks(983),
                            Description = "Dolores aliquid quos aut voluptatum.",
                            FinishedAt = new DateTime(2021, 10, 11, 1, 8, 52, 530, DateTimeKind.Local).AddTicks(760),
                            PerformerId = 7,
                            ProjectId = 20,
                            RenamedName = "Shaina",
                            State = 0
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 11, 18, 11, 23, 23, 563, DateTimeKind.Local).AddTicks(5877),
                            Description = "Et pariatur voluptates quo nam.",
                            PerformerId = 30,
                            ProjectId = 18,
                            RenamedName = "Kara",
                            State = 0
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 9, 28, 0, 51, 11, 965, DateTimeKind.Local).AddTicks(8382),
                            Description = "Vitae sit ea voluptatum id.",
                            FinishedAt = new DateTime(2022, 1, 9, 7, 48, 16, 560, DateTimeKind.Local).AddTicks(5932),
                            PerformerId = 14,
                            ProjectId = 6,
                            RenamedName = "Annamae",
                            State = 0
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 11, 15, 22, 25, 42, 934, DateTimeKind.Local).AddTicks(7413),
                            Description = "Sequi et dignissimos perferendis voluptatem.",
                            PerformerId = 12,
                            ProjectId = 14,
                            RenamedName = "Wilma",
                            State = 2
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 1, 18, 13, 35, 29, 460, DateTimeKind.Local).AddTicks(9324),
                            Description = "Quas et praesentium maxime et.",
                            PerformerId = 3,
                            ProjectId = 12,
                            RenamedName = "Annalise",
                            State = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 10, 18, 17, 37, 52, 352, DateTimeKind.Local).AddTicks(8849),
                            Description = "Distinctio sint quis aspernatur sunt.",
                            PerformerId = 28,
                            ProjectId = 7,
                            RenamedName = "Addison",
                            State = 2
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 5, 12, 3, 10, 27, 850, DateTimeKind.Local).AddTicks(7383),
                            Description = "Assumenda facilis et et non.",
                            FinishedAt = new DateTime(2022, 5, 31, 15, 25, 39, 224, DateTimeKind.Local).AddTicks(585),
                            PerformerId = 30,
                            ProjectId = 8,
                            RenamedName = "Eliza",
                            State = 3
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 6, 7, 13, 41, 8, 575, DateTimeKind.Local).AddTicks(9608),
                            Description = "Ratione ut pariatur unde et.",
                            FinishedAt = new DateTime(2022, 1, 24, 2, 1, 6, 521, DateTimeKind.Local).AddTicks(7473),
                            PerformerId = 8,
                            ProjectId = 6,
                            RenamedName = "Marlene",
                            State = 3
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 1, 15, 7, 14, 5, 599, DateTimeKind.Local).AddTicks(583),
                            Description = "Magni provident qui culpa quasi.",
                            FinishedAt = new DateTime(2022, 5, 26, 3, 50, 5, 606, DateTimeKind.Local).AddTicks(1576),
                            PerformerId = 7,
                            ProjectId = 6,
                            RenamedName = "Jewel",
                            State = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 12, 23, 5, 46, 47, 819, DateTimeKind.Local).AddTicks(3587),
                            Description = "Sed ea voluptatum quia incidunt.",
                            FinishedAt = new DateTime(2022, 7, 8, 7, 0, 48, 458, DateTimeKind.Local).AddTicks(794),
                            PerformerId = 26,
                            ProjectId = 12,
                            RenamedName = "Bret",
                            State = 2
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 12, 15, 19, 13, 11, 383, DateTimeKind.Local).AddTicks(803),
                            Description = "Nemo molestiae natus occaecati architecto.",
                            FinishedAt = new DateTime(2022, 7, 3, 17, 41, 9, 138, DateTimeKind.Local).AddTicks(1553),
                            PerformerId = 17,
                            ProjectId = 18,
                            RenamedName = "Zack",
                            State = 2
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 8, 5, 14, 4, 59, 682, DateTimeKind.Local).AddTicks(5130),
                            Description = "Sint delectus qui recusandae commodi.",
                            FinishedAt = new DateTime(2021, 9, 1, 17, 19, 38, 966, DateTimeKind.Local).AddTicks(2063),
                            PerformerId = 18,
                            ProjectId = 17,
                            RenamedName = "Taya",
                            State = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 9, 9, 20, 39, 28, 109, DateTimeKind.Local).AddTicks(3355),
                            Description = "Consectetur molestiae sit odit ipsa.",
                            FinishedAt = new DateTime(2022, 6, 22, 6, 15, 50, 245, DateTimeKind.Local).AddTicks(9459),
                            PerformerId = 5,
                            ProjectId = 5,
                            RenamedName = "Davon",
                            State = 3
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2022, 3, 25, 1, 29, 47, 888, DateTimeKind.Local).AddTicks(566),
                            Description = "Aperiam est illo vitae quos.",
                            FinishedAt = new DateTime(2022, 1, 10, 21, 37, 5, 309, DateTimeKind.Local).AddTicks(7236),
                            PerformerId = 19,
                            ProjectId = 9,
                            RenamedName = "Edmond",
                            State = 2
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 9, 26, 16, 58, 38, 612, DateTimeKind.Local).AddTicks(330),
                            Description = "Modi ipsum ad architecto incidunt.",
                            FinishedAt = new DateTime(2022, 4, 21, 22, 46, 0, 2, DateTimeKind.Local).AddTicks(9414),
                            PerformerId = 22,
                            ProjectId = 19,
                            RenamedName = "Colten",
                            State = 0
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 9, 26, 16, 34, 55, 859, DateTimeKind.Local).AddTicks(331),
                            Description = "Ipsam officia eveniet consequatur et.",
                            FinishedAt = new DateTime(2021, 10, 24, 7, 50, 56, 538, DateTimeKind.Local).AddTicks(4518),
                            PerformerId = 12,
                            ProjectId = 16,
                            RenamedName = "Kaycee",
                            State = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2022, 2, 14, 3, 11, 16, 236, DateTimeKind.Local).AddTicks(9983),
                            Description = "Corporis at omnis voluptatem ea.",
                            PerformerId = 13,
                            ProjectId = 11,
                            RenamedName = "Hubert",
                            State = 2
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2022, 4, 21, 10, 5, 45, 374, DateTimeKind.Local).AddTicks(5178),
                            Description = "Consequuntur nesciunt ipsa quod aperiam.",
                            FinishedAt = new DateTime(2021, 12, 14, 23, 33, 21, 841, DateTimeKind.Local).AddTicks(8890),
                            PerformerId = 10,
                            ProjectId = 11,
                            RenamedName = "Aimee",
                            State = 0
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2022, 5, 16, 3, 5, 48, 908, DateTimeKind.Local).AddTicks(846),
                            Description = "Maxime rerum accusamus quia eligendi.",
                            PerformerId = 30,
                            ProjectId = 18,
                            RenamedName = "Carlie",
                            State = 1
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2022, 1, 22, 2, 37, 43, 931, DateTimeKind.Local).AddTicks(2325),
                            Description = "Aliquam aut corporis ratione porro.",
                            FinishedAt = new DateTime(2021, 11, 3, 14, 16, 21, 694, DateTimeKind.Local).AddTicks(2880),
                            PerformerId = 12,
                            ProjectId = 11,
                            RenamedName = "Antoinette",
                            State = 3
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2022, 6, 5, 6, 36, 15, 177, DateTimeKind.Local).AddTicks(1026),
                            Description = "Voluptatum qui modi ex molestias.",
                            FinishedAt = new DateTime(2021, 12, 9, 2, 38, 18, 771, DateTimeKind.Local).AddTicks(6990),
                            PerformerId = 23,
                            ProjectId = 11,
                            RenamedName = "Lucio",
                            State = 0
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 7, 28, 13, 32, 37, 566, DateTimeKind.Local).AddTicks(1593),
                            Description = "Sapiente ducimus molestias ut quibusdam.",
                            FinishedAt = new DateTime(2021, 12, 10, 6, 32, 56, 906, DateTimeKind.Local).AddTicks(601),
                            PerformerId = 19,
                            ProjectId = 2,
                            RenamedName = "Tina",
                            State = 3
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2022, 3, 1, 3, 52, 18, 930, DateTimeKind.Local).AddTicks(2263),
                            Description = "Quasi voluptatibus enim aliquid atque.",
                            PerformerId = 6,
                            ProjectId = 1,
                            RenamedName = "Tristian",
                            State = 3
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 9, 30, 21, 53, 13, 136, DateTimeKind.Local).AddTicks(5527),
                            Description = "Officia velit libero numquam quia.",
                            FinishedAt = new DateTime(2021, 10, 1, 11, 27, 48, 902, DateTimeKind.Local).AddTicks(5408),
                            PerformerId = 1,
                            ProjectId = 17,
                            RenamedName = "Lucio",
                            State = 3
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2022, 6, 2, 4, 4, 38, 32, DateTimeKind.Local).AddTicks(4676),
                            Description = "Dolorem non sit nesciunt inventore.",
                            PerformerId = 23,
                            ProjectId = 17,
                            RenamedName = "Rasheed",
                            State = 2
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 11, 26, 4, 22, 37, 859, DateTimeKind.Local).AddTicks(5926),
                            Description = "Perferendis porro perferendis qui eaque.",
                            FinishedAt = new DateTime(2021, 9, 14, 15, 29, 39, 321, DateTimeKind.Local).AddTicks(4067),
                            PerformerId = 29,
                            ProjectId = 14,
                            RenamedName = "Juanita",
                            State = 0
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 8, 23, 22, 6, 3, 352, DateTimeKind.Local).AddTicks(5189),
                            Description = "Magnam ab illo voluptatum similique.",
                            PerformerId = 19,
                            ProjectId = 13,
                            RenamedName = "Mossie",
                            State = 1
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2022, 1, 12, 14, 6, 7, 846, DateTimeKind.Local).AddTicks(6381),
                            Description = "Culpa corporis autem voluptas deserunt.",
                            PerformerId = 4,
                            ProjectId = 9,
                            RenamedName = "Augusta",
                            State = 1
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2022, 3, 9, 21, 34, 38, 88, DateTimeKind.Local).AddTicks(4542),
                            Description = "Quaerat et voluptates est veniam.",
                            FinishedAt = new DateTime(2021, 8, 11, 13, 12, 35, 641, DateTimeKind.Local).AddTicks(5335),
                            PerformerId = 8,
                            ProjectId = 19,
                            RenamedName = "Donavon",
                            State = 3
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2022, 2, 16, 9, 31, 3, 280, DateTimeKind.Local).AddTicks(1759),
                            Description = "Eum pariatur est corrupti quisquam.",
                            FinishedAt = new DateTime(2022, 4, 8, 1, 0, 32, 956, DateTimeKind.Local).AddTicks(4401),
                            PerformerId = 21,
                            ProjectId = 12,
                            RenamedName = "Assunta",
                            State = 3
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2021, 12, 27, 11, 58, 21, 26, DateTimeKind.Local).AddTicks(5792),
                            Description = "Et temporibus repellendus at dolorem.",
                            PerformerId = 6,
                            ProjectId = 18,
                            RenamedName = "Sabrina",
                            State = 3
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2022, 3, 3, 13, 47, 31, 911, DateTimeKind.Local).AddTicks(5873),
                            Description = "Necessitatibus aut sunt voluptatibus reprehenderit.",
                            PerformerId = 25,
                            ProjectId = 9,
                            RenamedName = "Valentine",
                            State = 2
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2021, 12, 25, 4, 53, 19, 53, DateTimeKind.Local).AddTicks(6423),
                            Description = "Sapiente numquam ut quo consequuntur.",
                            PerformerId = 21,
                            ProjectId = 20,
                            RenamedName = "Ansel",
                            State = 2
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2021, 12, 26, 11, 57, 30, 681, DateTimeKind.Local).AddTicks(4984),
                            Description = "Sed atque odio laudantium perferendis.",
                            FinishedAt = new DateTime(2021, 12, 17, 7, 21, 20, 115, DateTimeKind.Local).AddTicks(1051),
                            PerformerId = 16,
                            ProjectId = 17,
                            RenamedName = "Emily",
                            State = 2
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2022, 3, 20, 8, 11, 15, 894, DateTimeKind.Local).AddTicks(1564),
                            Description = "Voluptatem aut quis laborum nulla.",
                            FinishedAt = new DateTime(2021, 8, 19, 5, 24, 0, 288, DateTimeKind.Local).AddTicks(9235),
                            PerformerId = 1,
                            ProjectId = 2,
                            RenamedName = "Icie",
                            State = 2
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2021, 8, 12, 1, 50, 53, 406, DateTimeKind.Local).AddTicks(5734),
                            Description = "Sint ab aut rerum perferendis.",
                            FinishedAt = new DateTime(2021, 9, 30, 10, 11, 36, 12, DateTimeKind.Local).AddTicks(357),
                            PerformerId = 3,
                            ProjectId = 1,
                            RenamedName = "Camila",
                            State = 1
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2021, 12, 8, 18, 40, 37, 811, DateTimeKind.Local).AddTicks(8014),
                            Description = "Saepe fugit saepe consequuntur suscipit.",
                            FinishedAt = new DateTime(2022, 5, 22, 13, 26, 8, 70, DateTimeKind.Local).AddTicks(9480),
                            PerformerId = 7,
                            ProjectId = 5,
                            RenamedName = "Bernadine",
                            State = 2
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2021, 12, 15, 23, 31, 21, 803, DateTimeKind.Local).AddTicks(1274),
                            Description = "Vitae facere repudiandae quasi sed.",
                            FinishedAt = new DateTime(2022, 5, 4, 13, 47, 28, 350, DateTimeKind.Local).AddTicks(696),
                            PerformerId = 17,
                            ProjectId = 5,
                            RenamedName = "Edyth",
                            State = 0
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2022, 2, 18, 3, 9, 44, 711, DateTimeKind.Local).AddTicks(9044),
                            Description = "Qui est consequatur aspernatur ipsam.",
                            FinishedAt = new DateTime(2021, 12, 3, 9, 33, 8, 165, DateTimeKind.Local).AddTicks(6105),
                            PerformerId = 3,
                            ProjectId = 13,
                            RenamedName = "Raleigh",
                            State = 0
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2021, 12, 17, 9, 2, 3, 475, DateTimeKind.Local).AddTicks(900),
                            Description = "Quo possimus eum assumenda esse.",
                            FinishedAt = new DateTime(2021, 9, 6, 17, 0, 57, 925, DateTimeKind.Local).AddTicks(8901),
                            PerformerId = 16,
                            ProjectId = 11,
                            RenamedName = "Nichole",
                            State = 3
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2021, 11, 7, 21, 50, 57, 182, DateTimeKind.Local).AddTicks(6934),
                            Description = "Suscipit rerum quis consequatur fuga.",
                            FinishedAt = new DateTime(2022, 7, 3, 22, 41, 48, 955, DateTimeKind.Local).AddTicks(6810),
                            PerformerId = 28,
                            ProjectId = 1,
                            RenamedName = "Sibyl",
                            State = 0
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2021, 7, 27, 14, 46, 7, 994, DateTimeKind.Local).AddTicks(4109),
                            Description = "Ab voluptatem rerum fugiat explicabo.",
                            PerformerId = 18,
                            ProjectId = 19,
                            RenamedName = "Marisa",
                            State = 2
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2022, 4, 6, 19, 44, 9, 761, DateTimeKind.Local).AddTicks(7433),
                            Description = "Eum non tempore porro itaque.",
                            PerformerId = 28,
                            ProjectId = 17,
                            RenamedName = "Casimer",
                            State = 3
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2022, 2, 11, 4, 25, 32, 897, DateTimeKind.Local).AddTicks(3132),
                            Description = "Delectus cumque voluptatem perferendis quia.",
                            PerformerId = 2,
                            ProjectId = 14,
                            RenamedName = "Skylar",
                            State = 3
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2021, 10, 1, 1, 55, 40, 23, DateTimeKind.Local).AddTicks(5472),
                            Description = "Sequi eos magni ea enim.",
                            FinishedAt = new DateTime(2021, 9, 23, 7, 54, 29, 536, DateTimeKind.Local).AddTicks(1992),
                            PerformerId = 22,
                            ProjectId = 18,
                            RenamedName = "Deja",
                            State = 3
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2022, 3, 28, 3, 18, 36, 259, DateTimeKind.Local).AddTicks(2545),
                            Description = "Accusamus sint ea dolorum incidunt.",
                            FinishedAt = new DateTime(2021, 11, 28, 14, 40, 1, 287, DateTimeKind.Local).AddTicks(4509),
                            PerformerId = 25,
                            ProjectId = 6,
                            RenamedName = "Jillian",
                            State = 1
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2022, 1, 26, 6, 40, 13, 100, DateTimeKind.Local).AddTicks(5245),
                            Description = "Ut facilis necessitatibus et libero.",
                            FinishedAt = new DateTime(2021, 9, 5, 0, 59, 23, 487, DateTimeKind.Local).AddTicks(8396),
                            PerformerId = 20,
                            ProjectId = 15,
                            RenamedName = "Ladarius",
                            State = 2
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2022, 2, 12, 1, 59, 20, 810, DateTimeKind.Local).AddTicks(5676),
                            Description = "Ipsam qui dolor impedit earum.",
                            FinishedAt = new DateTime(2021, 10, 19, 10, 7, 14, 833, DateTimeKind.Local).AddTicks(7157),
                            PerformerId = 28,
                            ProjectId = 11,
                            RenamedName = "Marina",
                            State = 2
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2021, 8, 5, 22, 20, 56, 495, DateTimeKind.Local).AddTicks(6810),
                            Description = "Voluptatem debitis placeat dolores aperiam.",
                            PerformerId = 15,
                            ProjectId = 6,
                            RenamedName = "Russell",
                            State = 1
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2021, 12, 31, 10, 16, 5, 810, DateTimeKind.Local).AddTicks(4854),
                            Description = "Omnis quas at nihil ut.",
                            FinishedAt = new DateTime(2021, 11, 10, 15, 2, 44, 810, DateTimeKind.Local).AddTicks(2100),
                            PerformerId = 22,
                            ProjectId = 10,
                            RenamedName = "Clint",
                            State = 3
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2022, 3, 28, 14, 4, 43, 949, DateTimeKind.Local).AddTicks(8253),
                            Description = "Doloribus error qui nulla qui.",
                            FinishedAt = new DateTime(2022, 1, 6, 15, 39, 5, 434, DateTimeKind.Local).AddTicks(1581),
                            PerformerId = 22,
                            ProjectId = 18,
                            RenamedName = "Candida",
                            State = 3
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2022, 6, 6, 7, 25, 48, 387, DateTimeKind.Local).AddTicks(7894),
                            Description = "Qui et eum a harum.",
                            PerformerId = 10,
                            ProjectId = 3,
                            RenamedName = "Ofelia",
                            State = 3
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2021, 9, 5, 13, 3, 4, 805, DateTimeKind.Local).AddTicks(8293),
                            Description = "Ut sequi enim aut corporis.",
                            FinishedAt = new DateTime(2022, 2, 9, 5, 5, 19, 462, DateTimeKind.Local).AddTicks(9678),
                            PerformerId = 24,
                            ProjectId = 16,
                            RenamedName = "Mariela",
                            State = 2
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2021, 10, 26, 1, 35, 31, 589, DateTimeKind.Local).AddTicks(4375),
                            Description = "Et ut eius vel enim.",
                            FinishedAt = new DateTime(2021, 11, 28, 5, 16, 15, 326, DateTimeKind.Local).AddTicks(3873),
                            PerformerId = 11,
                            ProjectId = 3,
                            RenamedName = "Camilla",
                            State = 1
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2021, 9, 5, 6, 36, 50, 929, DateTimeKind.Local).AddTicks(50),
                            Description = "Repellat unde laboriosam assumenda quas.",
                            FinishedAt = new DateTime(2021, 8, 31, 13, 31, 12, 393, DateTimeKind.Local).AddTicks(3727),
                            PerformerId = 27,
                            ProjectId = 7,
                            RenamedName = "Jay",
                            State = 1
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2022, 7, 1, 11, 27, 41, 848, DateTimeKind.Local).AddTicks(8136),
                            Description = "Cumque praesentium laudantium sit labore.",
                            FinishedAt = new DateTime(2021, 11, 10, 5, 25, 42, 784, DateTimeKind.Local).AddTicks(6361),
                            PerformerId = 1,
                            ProjectId = 12,
                            RenamedName = "Linnea",
                            State = 1
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2022, 1, 16, 8, 18, 24, 213, DateTimeKind.Local).AddTicks(2057),
                            Description = "Officiis et quod laboriosam unde.",
                            FinishedAt = new DateTime(2021, 9, 9, 2, 46, 37, 667, DateTimeKind.Local).AddTicks(6091),
                            PerformerId = 7,
                            ProjectId = 1,
                            RenamedName = "Carolyne",
                            State = 3
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2021, 10, 11, 4, 20, 32, 24, DateTimeKind.Local).AddTicks(447),
                            Description = "Autem quis eveniet et dolorem.",
                            FinishedAt = new DateTime(2022, 3, 13, 14, 18, 28, 945, DateTimeKind.Local).AddTicks(6114),
                            PerformerId = 14,
                            ProjectId = 1,
                            RenamedName = "Dominique",
                            State = 3
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2021, 7, 22, 0, 29, 1, 969, DateTimeKind.Local).AddTicks(265),
                            Description = "Autem alias illo autem numquam.",
                            PerformerId = 21,
                            ProjectId = 19,
                            RenamedName = "Lelah",
                            State = 0
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2022, 2, 21, 16, 49, 57, 858, DateTimeKind.Local).AddTicks(970),
                            Description = "Possimus suscipit distinctio id autem.",
                            FinishedAt = new DateTime(2021, 12, 1, 22, 43, 11, 138, DateTimeKind.Local).AddTicks(6891),
                            PerformerId = 15,
                            ProjectId = 19,
                            RenamedName = "Kendra",
                            State = 3
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2022, 2, 28, 12, 57, 34, 715, DateTimeKind.Local).AddTicks(9623),
                            Description = "Voluptates sed dolorem commodi qui.",
                            FinishedAt = new DateTime(2022, 1, 1, 18, 36, 3, 442, DateTimeKind.Local).AddTicks(5258),
                            PerformerId = 13,
                            ProjectId = 4,
                            RenamedName = "Laurianne",
                            State = 1
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2021, 8, 22, 22, 41, 58, 136, DateTimeKind.Local).AddTicks(1492),
                            Description = "Corporis id sit at iste.",
                            FinishedAt = new DateTime(2022, 1, 12, 12, 40, 3, 988, DateTimeKind.Local).AddTicks(474),
                            PerformerId = 12,
                            ProjectId = 15,
                            RenamedName = "Vickie",
                            State = 1
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2021, 10, 5, 22, 41, 35, 25, DateTimeKind.Local).AddTicks(4505),
                            Description = "Quo aspernatur ullam est ut.",
                            FinishedAt = new DateTime(2022, 1, 28, 19, 2, 43, 699, DateTimeKind.Local).AddTicks(3853),
                            PerformerId = 24,
                            ProjectId = 5,
                            RenamedName = "Ebony",
                            State = 1
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2022, 3, 24, 10, 1, 37, 267, DateTimeKind.Local).AddTicks(7511),
                            Description = "Earum dolor quasi sint asperiores.",
                            PerformerId = 29,
                            ProjectId = 17,
                            RenamedName = "Jermaine",
                            State = 3
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2021, 12, 29, 18, 6, 5, 11, DateTimeKind.Local).AddTicks(5622),
                            Description = "Sit fuga molestias impedit quidem.",
                            FinishedAt = new DateTime(2022, 1, 5, 7, 15, 49, 770, DateTimeKind.Local).AddTicks(6404),
                            PerformerId = 11,
                            ProjectId = 20,
                            RenamedName = "Kendra",
                            State = 0
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2021, 9, 14, 17, 40, 28, 115, DateTimeKind.Local).AddTicks(304),
                            Description = "Iusto voluptate aliquid nam perspiciatis.",
                            FinishedAt = new DateTime(2021, 12, 21, 11, 40, 25, 593, DateTimeKind.Local).AddTicks(3328),
                            PerformerId = 17,
                            ProjectId = 10,
                            RenamedName = "Vinnie",
                            State = 1
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2021, 10, 7, 11, 33, 1, 342, DateTimeKind.Local).AddTicks(6953),
                            Description = "Voluptas et aut dolore rerum.",
                            FinishedAt = new DateTime(2022, 4, 24, 17, 43, 36, 491, DateTimeKind.Local).AddTicks(6393),
                            PerformerId = 26,
                            ProjectId = 13,
                            RenamedName = "Jeramie",
                            State = 3
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2021, 12, 20, 10, 30, 11, 462, DateTimeKind.Local).AddTicks(3019),
                            Description = "Neque ullam enim ex ex.",
                            FinishedAt = new DateTime(2021, 11, 17, 12, 24, 37, 260, DateTimeKind.Local).AddTicks(8605),
                            PerformerId = 6,
                            ProjectId = 11,
                            RenamedName = "Alexanne",
                            State = 1
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2021, 7, 21, 21, 35, 30, 892, DateTimeKind.Local).AddTicks(7380),
                            Description = "Voluptatem non soluta aut similique.",
                            FinishedAt = new DateTime(2022, 2, 23, 5, 27, 52, 511, DateTimeKind.Local).AddTicks(5443),
                            PerformerId = 22,
                            ProjectId = 7,
                            RenamedName = "Dalton",
                            State = 3
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2022, 5, 24, 8, 0, 51, 727, DateTimeKind.Local).AddTicks(215),
                            Description = "Sunt quo qui vero sit.",
                            FinishedAt = new DateTime(2021, 11, 21, 19, 10, 49, 294, DateTimeKind.Local).AddTicks(4819),
                            PerformerId = 1,
                            ProjectId = 6,
                            RenamedName = "Pascale",
                            State = 2
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2022, 3, 16, 22, 29, 45, 938, DateTimeKind.Local).AddTicks(5997),
                            Description = "Expedita velit enim quis labore.",
                            PerformerId = 17,
                            ProjectId = 5,
                            RenamedName = "Chance",
                            State = 0
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2021, 10, 7, 11, 23, 38, 297, DateTimeKind.Local).AddTicks(1239),
                            Description = "Ut maiores distinctio voluptate error.",
                            PerformerId = 23,
                            ProjectId = 3,
                            RenamedName = "Wanda",
                            State = 2
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2021, 8, 19, 0, 44, 26, 173, DateTimeKind.Local).AddTicks(8013),
                            Description = "Aut voluptates eius voluptatem deleniti.",
                            PerformerId = 4,
                            ProjectId = 4,
                            RenamedName = "Victoria",
                            State = 3
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2021, 9, 4, 8, 11, 45, 766, DateTimeKind.Local).AddTicks(2664),
                            Description = "Accusantium harum quasi vel doloribus.",
                            FinishedAt = new DateTime(2022, 6, 25, 7, 25, 57, 586, DateTimeKind.Local).AddTicks(6667),
                            PerformerId = 5,
                            ProjectId = 11,
                            RenamedName = "Emmitt",
                            State = 3
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2021, 7, 30, 17, 56, 9, 183, DateTimeKind.Local).AddTicks(2126),
                            Description = "Architecto et quos corporis quos.",
                            FinishedAt = new DateTime(2022, 4, 23, 23, 18, 39, 480, DateTimeKind.Local).AddTicks(8960),
                            PerformerId = 4,
                            ProjectId = 13,
                            RenamedName = "Adrien",
                            State = 1
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2021, 10, 31, 0, 26, 24, 553, DateTimeKind.Local).AddTicks(6592),
                            Description = "Quia eveniet sit in officiis.",
                            FinishedAt = new DateTime(2022, 6, 5, 9, 27, 29, 568, DateTimeKind.Local).AddTicks(7402),
                            PerformerId = 17,
                            ProjectId = 14,
                            RenamedName = "Oswald",
                            State = 3
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 24, 12, 56, 14, 738, DateTimeKind.Local).AddTicks(5050),
                            Name = "O'Keefe - Bruen"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 4, 8, 21, 59, 20, 434, DateTimeKind.Local).AddTicks(2161),
                            Name = "Jenkins - Spinka"
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2022, 2, 9, 0, 24, 24, 604, DateTimeKind.Local).AddTicks(8922),
                            Email = "Berta72@gmail.com",
                            FirstName = "Maegan",
                            LastName = "Ruecker",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 1, 15, 3, 0, 0, 557, DateTimeKind.Local).AddTicks(8873),
                            Email = "Damien.Yundt96@yahoo.com",
                            FirstName = "Eriberto",
                            LastName = "Heathcote",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2021, 11, 22, 0, 49, 52, 274, DateTimeKind.Local).AddTicks(5391),
                            Email = "Randy1@hotmail.com",
                            FirstName = "Norval",
                            LastName = "Torp",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2022, 2, 14, 20, 22, 9, 60, DateTimeKind.Local).AddTicks(3056),
                            Email = "Harley80@gmail.com",
                            FirstName = "Adrien",
                            LastName = "Torphy",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(2021, 12, 11, 2, 29, 27, 419, DateTimeKind.Local).AddTicks(9245),
                            Email = "Salma_Bechtelar@gmail.com",
                            FirstName = "Cassandre",
                            LastName = "Wisoky",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            BirthDay = new DateTime(2021, 11, 27, 7, 48, 54, 571, DateTimeKind.Local).AddTicks(7668),
                            Email = "Edyth.Hackett@gmail.com",
                            FirstName = "Briana",
                            LastName = "Donnelly",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            BirthDay = new DateTime(2022, 5, 8, 14, 37, 2, 689, DateTimeKind.Local).AddTicks(599),
                            Email = "Xander.Flatley84@hotmail.com",
                            FirstName = "Gerhard",
                            LastName = "Leffler",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            BirthDay = new DateTime(2021, 9, 26, 19, 17, 55, 563, DateTimeKind.Local).AddTicks(4567),
                            Email = "Virgil_Quigley@hotmail.com",
                            FirstName = "Easton",
                            LastName = "Padberg",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            BirthDay = new DateTime(2022, 7, 2, 16, 31, 48, 62, DateTimeKind.Local).AddTicks(3251),
                            Email = "Britney.Gislason@yahoo.com",
                            FirstName = "Dedric",
                            LastName = "Ebert",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            BirthDay = new DateTime(2021, 8, 10, 18, 52, 54, 5, DateTimeKind.Local).AddTicks(7418),
                            Email = "Kassandra.Langosh68@yahoo.com",
                            FirstName = "Lukas",
                            LastName = "Tillman",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            BirthDay = new DateTime(2022, 4, 13, 12, 18, 2, 686, DateTimeKind.Local).AddTicks(7861),
                            Email = "Everette81@hotmail.com",
                            FirstName = "Tessie",
                            LastName = "Homenick",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            BirthDay = new DateTime(2021, 12, 30, 12, 57, 38, 122, DateTimeKind.Local).AddTicks(2060),
                            Email = "Green_Kling@yahoo.com",
                            FirstName = "Vickie",
                            LastName = "Blick",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            BirthDay = new DateTime(2021, 10, 23, 13, 25, 8, 831, DateTimeKind.Local).AddTicks(6597),
                            Email = "Terrance14@hotmail.com",
                            FirstName = "Mya",
                            LastName = "Cronin",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 14,
                            BirthDay = new DateTime(2021, 12, 9, 10, 14, 23, 507, DateTimeKind.Local).AddTicks(3566),
                            Email = "Kody.McKenzie@gmail.com",
                            FirstName = "Luis",
                            LastName = "Shanahan",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 15,
                            BirthDay = new DateTime(2022, 4, 7, 2, 38, 25, 532, DateTimeKind.Local).AddTicks(3802),
                            Email = "Okey8@yahoo.com",
                            FirstName = "Francesca",
                            LastName = "Koelpin",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            BirthDay = new DateTime(2022, 5, 3, 0, 2, 3, 144, DateTimeKind.Local).AddTicks(320),
                            Email = "Grant.Schowalter83@hotmail.com",
                            FirstName = "Otho",
                            LastName = "Armstrong",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            BirthDay = new DateTime(2021, 12, 31, 15, 34, 51, 145, DateTimeKind.Local).AddTicks(6945),
                            Email = "Ignatius4@yahoo.com",
                            FirstName = "Madge",
                            LastName = "Schamberger",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 18,
                            BirthDay = new DateTime(2021, 9, 3, 20, 51, 45, 475, DateTimeKind.Local).AddTicks(480),
                            Email = "Jaclyn.Hodkiewicz14@gmail.com",
                            FirstName = "Mona",
                            LastName = "Crona",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 19,
                            BirthDay = new DateTime(2021, 9, 16, 9, 16, 27, 718, DateTimeKind.Local).AddTicks(6167),
                            Email = "Eudora34@yahoo.com",
                            FirstName = "Malika",
                            LastName = "Yost",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 20,
                            BirthDay = new DateTime(2021, 7, 25, 9, 57, 16, 633, DateTimeKind.Local).AddTicks(5720),
                            Email = "Roberto90@yahoo.com",
                            FirstName = "Jessie",
                            LastName = "Pacocha",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            BirthDay = new DateTime(2021, 10, 1, 18, 57, 23, 41, DateTimeKind.Local).AddTicks(4936),
                            Email = "Clemmie38@hotmail.com",
                            FirstName = "Bettie",
                            LastName = "Gulgowski",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            BirthDay = new DateTime(2022, 4, 1, 17, 56, 41, 502, DateTimeKind.Local).AddTicks(9728),
                            Email = "Tiana_Jacobi33@yahoo.com",
                            FirstName = "Rey",
                            LastName = "Raynor",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 23,
                            BirthDay = new DateTime(2021, 10, 27, 9, 27, 45, 21, DateTimeKind.Local).AddTicks(4583),
                            Email = "Zackery59@hotmail.com",
                            FirstName = "Alicia",
                            LastName = "Schroeder",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 24,
                            BirthDay = new DateTime(2022, 2, 3, 17, 34, 37, 854, DateTimeKind.Local).AddTicks(3645),
                            Email = "Henderson.Mitchell@gmail.com",
                            FirstName = "Dale",
                            LastName = "McCullough",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 25,
                            BirthDay = new DateTime(2022, 3, 12, 16, 13, 31, 408, DateTimeKind.Local).AddTicks(6521),
                            Email = "Mellie40@gmail.com",
                            FirstName = "Stan",
                            LastName = "Moen",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 26,
                            BirthDay = new DateTime(2022, 4, 13, 11, 40, 58, 112, DateTimeKind.Local).AddTicks(5524),
                            Email = "Joel_Kulas2@yahoo.com",
                            FirstName = "Jabari",
                            LastName = "Willms",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 27,
                            BirthDay = new DateTime(2021, 11, 1, 0, 34, 10, 254, DateTimeKind.Local).AddTicks(7046),
                            Email = "Mabelle0@yahoo.com",
                            FirstName = "Kevin",
                            LastName = "Sauer",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 28,
                            BirthDay = new DateTime(2022, 3, 21, 14, 24, 46, 512, DateTimeKind.Local).AddTicks(3739),
                            Email = "Vladimir56@yahoo.com",
                            FirstName = "Iva",
                            LastName = "Beer",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 29,
                            BirthDay = new DateTime(2022, 1, 9, 3, 33, 12, 797, DateTimeKind.Local).AddTicks(7986),
                            Email = "Judah.White@yahoo.com",
                            FirstName = "Montana",
                            LastName = "Haag",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 30,
                            BirthDay = new DateTime(2022, 5, 3, 7, 26, 43, 314, DateTimeKind.Local).AddTicks(6800),
                            Email = "Patrick_Leannon@yahoo.com",
                            FirstName = "Blanca",
                            LastName = "Hessel",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Project", b =>
                {
                    b.HasOne("dz3Binary.DAL.Entities.User", "Author")
                        .WithMany("ProjectsCreated")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dz3Binary.DAL.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Task", b =>
                {
                    b.HasOne("dz3Binary.DAL.Entities.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dz3Binary.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dz3Binary.DAL.Entities.User", null)
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");

                    b.Navigation("Performer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.User", b =>
                {
                    b.HasOne("dz3Binary.DAL.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("dz3Binary.DAL.Entities.User", b =>
                {
                    b.Navigation("ProjectsCreated");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
